[package]
name = "stream_deck"
version = "0.1.0"
edition = "2018"

[dependencies]
common = { path = "../../../common" }
usb = { path = "../../../usb" }
file = { path = "../../../file" }
executor = { path = "../../../executor" }
macros = { path = "../../../macros" }