[package]
name = "cmsis_svd"
version = "0.1.0"
edition = "2018"

[dependencies]
automata = { path = "../../automata" }
regexp_macros = { path = "../../automata/regexp_macros" }
common = { path = "../../common" }
parsing = { path = "../../parsing" }
xml = { path = "../../format/xml" }