[package]
name = "container"
version = "0.1.0"
authors = ["Dennis Shtatnov <densht@gmail.com>"]
edition = "2018"

[dependencies]
common = { path = "../common" }
crypto = { path = "../crypto" }
nix = "0.21.0"
libc = "0.2.97"
protobuf = { path = "../protobuf" }
http = { path = "../http" }
macros = { path = "../macros" }
sstable = { path = "../sstable" }
compression = { path = "../compression" }
rpc = { path = "../rpc" }
google = { path = "../../third_party/google" }
async-std = "1.9.0"

[build-dependencies]
protobuf_compiler = { path = "../protobuf_compiler" }