[package]
name = "cluster_jbod"
version = "0.1.0"
edition = "2018"

[dependencies]
common = { path = "../../common" }
base_args = { path = "../../base/args" }
base_util = { path = "../../base/util" }
base_radix = { path = "../../base/radix" }
base_error = { path = "../../base/error" }
crypto = { path = "../../crypto" }
automata = { path = "../../automata" }
regexp_macros = { path = "../../automata/regexp_macros" }
protobuf = { path = "../../protobuf" }
http = { path = "../../http" }
macros = { path = "../../macros" }
compression = { path = "../../compression" }
cluster_client = { path = "../../cluster/client" }
rpc = { path = "../../rpc" }
rpc_util = { path = "../../rpc/util" }
net = { path = "../../net" }
protobuf_builtins = { path = "../../../third_party/protobuf_builtins" }
executor = { path = "../../executor" }
executor_multitask = { path = "../../executor/multitask" }
file = { path = "../../file" }
sys = { path = "../../sys" }
web = { path = "../../web" }
cluster_proto = { path = "../../cluster/proto" }
scpi = { path = "../../peripherals/scpi" }
peripherals_service = { path = "../../peripherals/service" }
cluster_jbod_proto = { path = "./proto" }
storage = { path = "../../storage" }

[features]
default = ["std"]
std = ["alloc"]
alloc = []