[package]
name = "rpi_fan_control"
version = "0.1.0"
authors = ["Dennis Shtatnov <densht@gmail.com>"]
edition = "2018"

[dependencies]
common = { path = "../common" }
nix = "0.21.0"
libc = "0.2.97"
lazy_static = "1.4.0"
protobuf = { path = "../protobuf" }
protobuf_json = { path = "../protobuf_json" }
macros = { path = "../macros" }
rpi = { path = "../rpi" }
rpc = { path = "../rpc" }
http = { path = "../http" }
rpc_util = { path = "../rpc_util" }
web = { path = "../web" }
json = { path = "../json" }
google = { path = "../../third_party/google" }

[build-dependencies]
protobuf_compiler = { path = "../protobuf_compiler" }

[features]
default = ["std"]
std = ["alloc"]
alloc = []