[package]
name = "tools"
version = "0.1.0"
edition = "2018"

[dependencies]
macros = { path = "../macros" }
automata = { path = "../automata" }
regexp_macros = { path = "../automata/regexp_macros" }
common = { path = "../common" }
base_radix = { path = "../base/radix" }
uuid = { path = "../uuid" }
http = { path = "../http" }
file = { path = "../file" }
asn = { path = "../asn" }
crypto = { path = "../crypto" }
executor = { path = "../executor" }

[features]
default = ["std"]
std = ["alloc"]
alloc = []