[package]
name = "net_iface"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../../common" }
net = { path = "../../net" }
file = { path = "../../file" }
executor = { path = "../../executor" }
macros = { path = "../../macros" }
libc = "0.2"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_NetworkManagement_IpHelper",
    "Win32_NetworkManagement_Ndis",
    "Win32_Networking_WinSock",
] }
windows-sys = { workspace = true }  

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.4"
objc2-core-foundation = "0.3.2"
objc2-system-configuration = "0.3.2"