// This file contains the core PeripheralRequest/PeripheralResponse types that
// will be exchanged with MCUs so need to work in memory constrained
// environments.

syntax = "proto3";

import "pkg/protobuf/compiler/proto/extensions.proto";

package peripherals;

message PeripheralRequest {
    uint32 peripheral_index = 1;

    // Sequence number for this request.
    // - Must be at least 1
    // - Mainly used right now to mark corresponding responses.
    // - Generally monotonic but may eventually wrap around back to 1.
    // - This value is only meaningful since the last USB reset.
    //
    // Internally a special value of 0 can be used on the MCU to indicate requests for which
    // responses don't need to be sent back to the host.
    uint32 request_sequence = 2;

    // TODO: Need to be able to query information about the MCU which which chip is used.
    // TODO: For long running requests with interrupts, we need to allow cancellation.

    // command to finalize the configs:
    // - may ask to persist across restarts.

    oneof command {
        ConfigureGPIO configure_gpio = 3;
        SetGPIOLevel set_gpio_level = 4;
        GetGPIOLevelRequest get_gpio_level = 5;

        // Unconfigures all peripherals and restores them back to the initial state
        // (input high-z).
        UnconfigureAll unconfigure_all = 7;

        ConfigurePWMRequest configure_pwm = 8;

        // TODO: Can probably be merged with the SetGPIOLevel one.
        SetPWMRequest set_pwm = 9;

        // Reads a tachometer GPIO input pin.
        // - Returns the period between consecutive falling edges in u32 microseconds.
        // - If it takes longer than 100ms to measure that, a timeout response is returned.
        //
        // TODO: Replace with generic support for getting interrupts with packet/event timing info.
        ReadTachometer read_tachometer = 10;

        // NOTE: This can be triggered on any peripheral
        bool measure_mcu_temperature = 11;

        // Should be called after all peripherals have been initialized to perform any
        // initialization actions that depend on having all pins wired out.
        //
        // Note that all other non-configuration commands are not allowed until this is called and
        // further configuration commands are not allowed after this is called.
        FinalizeConfigRequest finalize_config = 12;

        bool get_stack_pointer = 13;

        SleepRequest sleep = 14;

        // Returns the current time in u32 microseconds
        bool now = 15;

        // Cheapest possible request. Immediately returns an empty response.
        bool noop = 16;

        // Returns PeripheralInfoResponse
        bool info = 17;

        ConfigureUARTRequest configure_uart = 18;

        UARTTransmitRequest uart_transmit = 19;

        ConfigureStepperMotor configure_stepper = 20;

        StepperMotorMotion enqueue_stepper_motion = 21;

        bool get_clock_time = 22;

        bool get_stepper_motor_status = 23;

        ConfigureADCRequest configure_adc = 24;

        // Immediately start a single scalar ADC sample and return the result.
        SampleADCRequest sample_adc = 25;

        ConfigureNeopixelRequest configure_neopixel = 26;

        NeopixelTransfer neopixel_transfer = 27;

        // Check if the interrupt on a GPIO peripheral has fired.
        // The response will have a non-zero uint_val if it fired.
        bool poll_gpio_interrupt = 28;

        // Note that if a step was enqueued to be started, it will 
        // be marked as completed and it is undefined whether or not it actually
        // happened.
        bool clear_stepper_queue = 29;

        // Data is returned in the 'data_val' 
        uint32 read_adc_buffer = 31;
    }

    reserved 6;
}

// NOTE: If no data needs to be returned, this may be empty.
message PeripheralResponse {
    // Indicates which request this corresponds to.
    // Always non-zero.
    uint32 request_sequence = 1;

    enum ErrorCode {
        NO_ERROR = 0;

        // Something failed for an unexplainable reason. Maybe check the logs.
        UNKNOWN = 1;

        // Attempted to configure a non-existent pin.
        PIN_OUT_OF_RANGE = 2;

        // When configuring a peripheral: Indicates we don't support peripherals with this high of an index. 
        // When mutating a peripheral: Indicates the peripheral hasn't been configured.
        PERIPHERAL_OUT_OF_RANGE = 3;

        // We are unable to configure a pin to do something since it is already
        // reserved by another configured peripheral.
        PIN_ALREADY_CONFIGURED = 4;

        // Meanly for testing error responses.
        I_AM_A_TEAPOT = 5;

        // Either the direct peripheral or some shared resource (e.g. ADC controller) is locked for
        // exclusive use by some other in-flight request so starting this request will block.  
        RESOURCE_BUSY = 6;

        // The MCU doesn't know have to handle the command set in the request.
        UNSUPPORTED_COMMAND = 7;

        PERIPHERAL_ALREADY_CONFIGURED = 8;

        // Enable to process the request because we don't have any software or hardware resources.
        // e.g. If the PWM controller only supports 4 channels, attempting to configure a 5th will fail.
        RESOURCE_EXHAUSTED = 9;

        // The requested command can't be run on the peripheral as it was configured.
        INCOMPATIBLE_COMMAND = 10;

        TIMEOUT = 11;

        UNSUPPORTED_CONFIG = 12;

        // finalize_config hasn't been called yet.
        CONFIG_NOT_FINALIZED = 13;
    }

    ErrorCode error_code = 2;

    oneof response {
        // Used for basic integer responses.
        // - For GetGPIOLevel, this is 1 if the pin is high.
        uint32 uint_val = 3;

        float float_val = 4;

        bytes data_val = 5 [(dacha.max_length) = 32];

        uint64 wide_val = 6;

        StepperMotorStatus stepper_status = 7;

        ADCFormat adc_format = 8;
    }
}

// General information about what board we are talking to.
//
// NOTE: This is not meant to verbosely describe what each pin does. Instead this
// is meant to provide some enum board/chip ids so that the host can lookup that
// information elsewhere.
message PeripheralInfoResponse {
    enum Chip {
        UNKNOWN = 0;
        NRF52840 = 1;
    }
    Chip chip = 1;

    // Chip manufacturer specific revision code for the IC.
    uint32 chip_revision = 2;

    // TODO: Also report a binary build id.
}

message FinalizeConfigRequest {

}

message SleepRequest {
    uint32 micros = 1;

    bool return_error = 2;
}

message ConfigureGPIO {
    uint32 pin = 1;
    
    bool is_input = 2;
    
    bool pull_up = 3;

    bool pull_down = 4;

    // If not DISABLED, extra responses will be asyncronously sent back to the
    // host when the criteria is met.
    enum InterruptPolarity {
        DISABLED = 0;
        RISING_EDGE = 1;
        FALLING_EDGE = 2;
    }
    InterruptPolarity interrupt = 5;

    // If true, this pin defaults to high when it is an output.
    bool default_value = 6;
}

message SetGPIOLevel {
    // TODO: Also support HIGH-Z

    bool high = 1;
}

message GetGPIOLevelRequest {}

message GetGPIOLevelResponse {
    bool high = 1;
}

message UnconfigureAll {}


// Configures a single MCU pin as a PWM output.
message ConfigurePWMRequest {
    uint32 pin = 1;
    
    // Target PWM clock frequency in Hz.
    uint32 frequency = 2;

    // TODO: Need to implement this.
    bool inverted = 3;

    // If the PWM channel isn't updated in this amount of time, it will reset back to the default value.
    uint32 timeout_millis = 4;

    uint32 default_value = 5;
}

message SetPWMRequest {
    // Value with 16-bit resolution [0, 2^16) though the actual resolution will depend on the frequency
    // and hardware.
    uint32 value = 1;
}

message ConfigureUARTRequest {
    uint32 tx_pin = 1;

    uint32 rx_pin = 2;

    uint32 baud_rate = 3;
}

message UARTTransmitRequest {
    bytes data = 1 [(dacha.max_length) = 8];

    // After all of this data is sent, immediately turn on the receiver and wait for this number of 
    UARTReceiveRequest rx_after_tx = 2;
}

message UARTReceiveRequest {
    uint32 num_bytes = 1;
}

message ReadTachometer {}



message ConfigureStepperMotor {
    uint32 step_pin = 1;

    uint32 dir_pin = 2;
}

// TODO: Need to be able to stop all stepper operations immediately in an emergency stop mode.

message StepperMotorMotion {
    bool direction = 1;
    uint32 next_time = 2;
    uint32 next_velocity = 3;
    uint32 acceleration = 4;
    uint32 num_steps = 5;

    // Time at which the first step begins to move.
    // Assuming num_steps > 0, this is the time at which we first flip the 'STEP' pin. 
    // uint64 initial_time = 1;

    // NOTE: All steps in one motion are in the same direction.
    // bool forwards = 2;

    //uint32 num_steps = 3;

    // 
    //uint32 initial_time_delta = 4;

    // Amount the time delta between steps changes between each step.
    // int32 acceleration_per_step = 5;
}

message EnqueueStepperMotionRequest {
    StepperMotorMotion motion = 1;
}

message StepperMotorStatus {
    // Total number of completed steps.
    uint32 total_steps = 1;

    uint32 faults = 2;

    uint32 empty_queue_slots = 3;

    bool active = 4;
}

/*
ADC Commands:
- Configure
    - If given a sampling rate, I'll also reserve a full TIMER and one PPI channel to 
        - Timer: 
    - If given a threshold, set that up in the limits
        - Note that thresholds only help

- SingleSample
    - Sample once and immediately return the result inline in the response
        - Frequencies and thresholds are ignored
- SampleWindow
    - Collect a full window.
        - If a threshold is given, then the window won't be returned until we have at least one value that exceeds that.
    - Returns once the window is ready.
- CancelWindow
    - Mainly relevant for threshold based windows.
- ReadAnalogValues
    - Reads bytes from the analog buffer at some space.

*/

message ConfigureADCRequest {
    uint32 pin = 1;

    optional uint32 negative_pin = 2;

    bool measure_vdd = 3;

    // Expected maximum voltage value expected.
    // This is used to calibrate internal gain.
    float max_voltage = 4;

    // If true, then samples should be measured relative to Vdd if possible.
    bool vdd_reference = 5;

    // If zero, then use as high of a resolution as possible.
    uint32 max_bits_per_sample = 6;

    // When doing a window sample, this is the rate in Hz at which 
    uint32 sample_rate = 7;

    optional float trigger_above = 8;

    optional float trigger_below = 9; 

    // If true, sampling is immediately stopped if one of the triggers is hit.
    bool stop_on_trigger = 10;
}

message ADCFormat {
    uint32 bits_per_sample = 1;

    float units_per_volt = 2;
}

message SampleADCRequest {
    bool window = 1;
}


message ConfigureNeopixelRequest {
    uint32 pin = 1;
}

message NeopixelTransfer {
    bytes data = 1 [(dacha.max_length) = 16];
}


