syntax = "proto3";

package peripherals;

import "pkg/peripherals/proto/request.proto";

service Peripherals {
    rpc GetConfig (GetConfigRequest) returns (GetConfigResponse);

    rpc Execute (ExecuteRequest) returns (ExecuteResponse);

    rpc RunMacro (RunMacroRequest) returns (ExecuteResponse);
}

message RunMacroRequest {
    string name = 1;
}

message GetConfigRequest {

}

message GetConfigResponse {
    BoardConfig config = 1;

    PeripheralsState state = 2;
}

message ExecuteRequest {

    PeripheralRequest raw_request = 1;

    string peripheral_name = 2;

    bool sample_adc = 3;


}

message ExecuteResponse {
    PeripheralResponse response = 1;
    
    PeripheralsState state = 2;

}

message ResistorDivider {
    float top_resistor = 1;
    float bottom_resistor = 2;

    float max_input_voltage = 3;
}

message CurrentSenseResistor {
    float resistor_value = 1;
    float max_current = 2;
}

message Thermistor {
    string model = 1;
    float min_temp = 2;
    float max_temp = 3;
    float pull_up_resistance = 4;
}

message Tachometer {

}

message TMC2209Config {
    string step_peripheral = 1;
    string uart_peripheral = 2;
    string diag_peripheral = 3;
    string enable_peripheral = 4;

    string device_name = 5;

    uint32 addr = 6;
}

message ADCCalibration {
    float offset = 1;
    float scale = 2;
}


// Configuration for a board which exposes controllable hardware peripherals/pins.
message BoardConfig {
    string name = 1;

    string base_config = 2;

    uint32 product_id = 6;

    // TODO: Information on USB device/vendor ids.

    // TODO: Information on how to build binaries for this board.

    // TODO: Have some information for 
    message Pin {
        // Stable human readable name for the pin.
        string name = 1;
        
        // Other names for this pin. When merging a config with a base config,
        // this will be used to match up pins to base config pins.
        repeated string alias = 2;

        // Index to use when communicating with the MCU.
        // When merging with a base config, these will be copied from the
        // matching pin in the base config.
        optional uint32 index = 3;
    }
    repeated Pin pins = 3;


    message GPIOPeripheral {
        string pin_name = 1;
        ConfigureGPIO config = 2;
        Tachometer tachometer = 3;
    }

    message PWMPeripheral {
        string pin_name = 1;
        ConfigurePWMRequest config = 2;
    }

    message UARTPeripheral {
        string tx_pin_name = 1;
        string rx_pin_name = 2;
        ConfigureUARTRequest config = 3;
    }

    message StepperPeripheral {
        string step_pin_name = 1;
        string dir_pin_name = 2;
        ConfigureStepperMotor config = 3;
    }

    message NeopixelPeripheral {
        string pin_name = 1;
        ConfigureNeopixelRequest config = 2;
    }

    message ADCPeripheral {
        string pin_name = 1;

        string negative_pin_name = 2;

        // Raw ADC config that is used to setup the MCU.
        ConfigureADCRequest config = 3;

        // If given, then interprate the voltage measured on this pin as the output 
        // of a fixed resistor/voltage dividor with these resistance values.
        //
        // Any max voltage mentioned on 'config' will also be translated appropriately.
        ResistorDivider resistor_divider = 4;

        // If set, this ADC measures voltage across a current sense resistor with this resistance.
        //
        // Outputs should be converted to current values.
        CurrentSenseResistor current_sense_resistor = 5;

        Thermistor thermistor = 6;

        // NOTE: This is applied on the raw voltage level before other operations.
        ADCCalibration calibration = 7;
    }
    
    message ADCBufferPeripheral {
        AllocateADCBufferRequest config = 1;
    }

    message SPIPeripheral {
        string mosi_pin_name = 1;
        string miso_pin_name = 2;
        string sclk_pin_name = 3;
        string cs_pin_name = 4;
        ConfigureSPIRequest config = 5;
    }

    message I2CPeripheral {
        string sda_pin_name = 1;
        string scl_pin_name = 2;
        ConfigureI2CRequest config = 3;
    }

    message Peripheral {
        // Stable human readable name for the pin.
        string name = 1;

        // Index to use when communicating with the MCU
        optional uint32 index = 2;

        oneof config {
            GPIOPeripheral gpio = 3;
            PWMPeripheral pwm = 4;
            UARTPeripheral uart = 5;
            StepperPeripheral stepper = 6;
            NeopixelPeripheral neopixel = 7;
            ADCPeripheral adc = 8;
            SPIPeripheral spi = 9;
            ADCBufferPeripheral adc_buffer = 10;
            I2CPeripheral i2c = 11;
        }
    }
    repeated Peripheral peripherals = 4;


    message MacroCommand {
        string peripheral_name = 1;
        PeripheralRequest request = 2;
    }

    message Macro {
        string name = 1;
        repeated MacroCommand commands = 2;
    }

    repeated Macro macros = 5;

    // TODO: Want some diagram info on how to group the pins.
}


message PeripheralsState {
    repeated PeripheralState states = 1;
}

message PeripheralState {
    uint32 index = 1;

    oneof state {
        SetGPIOLevel gpio = 2;
        SetPWMRequest pwm = 3;
        ADCState adc = 4;
        TachometerState tachometer = 5;
    }
}


message ADCState {
    // TODO: Need better presense checking.
    float value = 1;
}

message TachometerState {
    float value = 1;
}
