[package]
name = "mocap_camera_core"
version = "0.1.0"
edition = "2024"

[dependencies]
base_util = { path = "../../../../base/util" }
common = { path = "../../../../common" }
vision = { path = "../../../" }
math = { path = "../../../../math" }
image = { path = "../../../../image" }
mocap_proto = { path = "../../proto" }
protobuf = { path = "../../../../protobuf" }