[package]
name = "bittorrent"
version = "0.1.0"
authors = ["Dennis Shtatnov <densht@gmail.com>"]
edition = "2018"

[dependencies]
automata = { path = "../automata" }
common = { path = "../common" }
parsing = { path = "../parsing" }