[package]
name = "git"
version = "0.1.0"
edition = "2018"

[dependencies]
common = { path = "../../common" }
base_error = { path = "../../base/error" }
executor = { path = "../../executor" }
macros = { path = "../../macros" }
file = { path = "../../file" }
http = { path = "../../http" }
crypto = { path = "../../crypto" }
base_radix = { path = "../../base/radix" }
base_util = { path = "../../base/util" }
parsing = { path = "../../parsing" }

[build-dependencies]
parsing_compiler = { path = "../../parsing/compiler" }
