[package]
name = "raft"
version = "0.1.0"
edition = "2018"

[dependencies]
common = { path = "../common" }
crypto = { path = "../crypto" }
http = { path = "../http" }
rpc = { path = "../rpc" }
rpc_util = { path = "../rpc_util" }
protobuf = { path = "../protobuf" }
sstable = { path = "../sstable" }
macros = { path = "../macros" }
protobuf_builtins = { path = "../../third_party/protobuf_builtins" }
libc = "0.2"
failure = "0.1.8"
executor = { path = "../executor" }
file = { path = "../file" }
net = { path = "../net" }
base_radix = { path = "../base/radix" }
raft_proto = { path = "./proto" }
raft_client = { path = "./client" }

[features]
default = ["std"]
std = ["alloc"]
alloc = []