[package]
name = "raft"
version = "0.1.0"
authors = ["Dennis Shtatnov <densht@gmail.com>"]
edition = "2018"

[dependencies]
common = { path = "../common" }
crypto = { path = "../crypto" }
http = { path = "../http" }
rpc = { path = "../rpc" }
protobuf = { path = "../protobuf" }
macros = { path = "../macros" }
google = { path = "../../third_party/google" }
fs2 = "0.4.3"
ctrlc = "3.1.1"
libc = "0.2"
byteorder = "1.3.2"

[build-dependencies]
protobuf_compiler = { path = "../protobuf_compiler" }