[package]
name = "raft"
version = "0.1.0"
authors = ["Dennis Shtatnov <densht@gmail.com>"]
edition = "2018"

[dependencies]
common = { path = "../common" }
crypto = { path = "../crypto" }
http = { path = "../http" }
rpc = { path = "../rpc" }
rpc_util = { path = "../rpc_util" }
protobuf = { path = "../protobuf" }
sstable = { path = "../sstable" }
macros = { path = "../macros" }
google = { path = "../../third_party/google" }
libc = "0.2"
nix = "0.21.0"
failure = "0.1.8"
executor = { path = "../executor" }
file = { path = "../file" }
net = { path = "../net" }

[build-dependencies]
protobuf_compiler = { path = "../protobuf_compiler" }

[features]
default = ["std"]
std = ["alloc"]
alloc = []