[package]
name = "sys"
version = "0.1.0"
edition = "2018"

[dependencies]
common = { path = "../common" }
parsing = { path = "../parsing" }
regexp_macros = { path = "../regexp_macros" }
automata = { path = "../automata" }
failure = "0.1.8"

[features]
default = ["std"]
std = ["alloc"]
alloc = []

[build-dependencies]
bindgen = "0.56.0"