[package]
name = "sys"
version = "0.1.0"
edition = "2018"

[dependencies]
common = { path = "../common" }
parsing = { path = "../parsing" }
elf = { path = "../elf" }
regexp_macros = { path = "../regexp_macros" }
automata = { path = "../automata" }
failure = "0.1.8"
peripherals_raw = { path = "../peripherals_raw" }

[features]
default = ["std"]
std = ["alloc"]
alloc = []

[build-dependencies]
bindgen = "0.63.0"