[workspace]

members = [
	"pkg/macros",
	"pkg/common",
	"pkg/reflection",
	"pkg/asn",
	"pkg/crypto",
	"pkg/parsing",
	"pkg/compression",
	"pkg/math",
	"pkg/protobuf",
	"pkg/automata",
	"pkg/http",
	"pkg/rpc",
	"pkg/image",
	"pkg/format",
	"third_party/pkix",
	"pkg/sstable",
	"pkg/graphics",
	"pkg/stadia_controller",
	"pkg/raft",
	"pkg/haystack",
	"pkg/emulator",
	"pkg/symbolic"
]

[profile.dev]
opt-level = 3

[profile.release]
lto = true
opt-level = 3
# panic = 'abort'
