[workspace]

members = [
	"pkg/macros",
	"pkg/common",
	"pkg/reflection",
	"pkg/asn",
	"pkg/crypto",
	"pkg/parsing",
	"pkg/parsing_compiler",
	"pkg/compression",
	"pkg/math",
	"pkg/protobuf_compiler",
	"pkg/protobuf",
	"pkg/automata",
	"pkg/http",
	"pkg/rpc",
	"pkg/image",
	"pkg/format",
	"third_party/pkix",
	"pkg/sstable",
	"pkg/graphics",
	"pkg/stadia_controller",
	"pkg/stream_deck",
	"pkg/raft",
	# "pkg/haystack",
	"pkg/emulator",
	"pkg/bittorrent",
	# "pkg/symbolic"
	"pkg/siglent",
	"third_party/openssl",
	"pkg/xml",
	"third_party/crates",
	"pkg/parsing_test"
]

[profile.dev]
#opt-level = 3
#lto = true

[profile.release]
lto = true
opt-level = 3 
# panic = 'abort'
debug = true
