[package]
name = "datalayer"
version = "0.1.0"
authors = ["Dennis Shtatnov <densht@gmail.com>"]

[[bin]]
name = "redis"
path = "src/redis.rs"

[[bin]]
name = "haystack"
path = "src/haystack/main.rs"


[dependencies]
#zstd = "0.4.21+zstd.1.3.7"
byteorder = "1.2.7"
#tokio = "0.1.13"
rand = "0.6.1"
crc32c = "0.4.0"
arrayref = "0.3.5"
hyper = "0.12.19"
futures = "0.1.25"
bytes = "0.4.11"
rocket = "0.4.0"
rocket_contrib = "0.4.0"
base64 = "0.10.0"
fs2 = "0.4.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

