[package]
name = "datalayer"
version = "0.1.0"
authors = ["Dennis Shtatnov <densht@gmail.com>"]

[build]
# Needed to make hashing remotely efficient
rustflags = "-C target-cpu=native"

[[bin]]
name = "redis"
path = "src/redis.rs"

[[bin]]
name = "haystack"
path = "src/haystack/main.rs"


[dependencies]
#zstd = "0.4.21+zstd.1.3.7"
byteorder = "1.2.7"
#tokio = "0.1.13"
rand = "0.6.1"
crc32c = "0.4.0"
arrayref = "0.3.5"

