[package]
name = "protobuf_compiler"
version = "0.1.0"
edition = "2018"

[dependencies]
automata = { path = "../../automata" }
base_radix = { path = "../../base/radix" }
regexp_macros = { path = "../../automata/regexp_macros" }
common = { path = "../../common" }
parsing = { path = "../../parsing" }
file = { path = "../../file" }
crypto = { path = "../../crypto" }
protobuf_core = { path = "../core" }
protobuf_dynamic = { path = "../dynamic", default-features = false }
protobuf_descriptor = { path = "../../../third_party/protobuf_descriptor", optional = true }

[features]
default = ["descriptors"]
descriptors = ["protobuf_descriptor", "protobuf_dynamic/descriptors"]