[package]
name = "protobuf_json"
version = "0.1.0"
edition = "2018"

[dependencies]
common = { path = "../../common" }
protobuf = { path = ".." }
macros = { path = "../../macros" }
json = { path = "../../format/json" }
protobuf_json_proto = { path = "./proto" }

[features]
default = ["std"]
std = ["alloc"]
alloc = []