[package]
name = "protobuf_core"
version = "0.1.0"
edition = "2018"

[dependencies]
common = { path = "../../common", default-features = false }
macros = { path = "../../macros" }
parsing = { path = "../../parsing", optional = true }
failure = { version = "0.1.8", optional = true }

[features]
default = ["std"]
alloc = ["common/alloc"]
std = ["alloc", "common/std", "failure", "parsing"]
