[package]
name = "regexp_macros"
version = "0.0.0"

[lib]
proc-macro = true

[dependencies]
automata = { path = ".." }
syn = { version = "1.0.23", features = ["extra-traits", "full"] }
quote = "1.0.6"
proc-macro2 = "1.0.13"