[package]
name = "ptp"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../../common" }
base_util = { path = "../../base/util" }
parsing = { path = "../../parsing" }
sys = { path = "../../sys" }
net = { path = "../../net" }
file = { path = "../../file" }
executor = { path = "../../executor" }
executor_multitask = { path = "../../executor/multitask" }
macros = { path = "../../macros" }
base_radix = { path = "../../base/radix" }
ptp_proto = { path = "./proto" }
crypto = { path = "../../crypto" }
http = { path = "../../http" }
cluster_client = { path = "../../cluster/client" }
cluster_proto = { path = "../../cluster/proto" }
rpc = { path = "../../rpc" }
rpc_util = { path = "../../rpc/util" }
protobuf = { path = "../../protobuf" }

[build-dependencies]
parsing_compiler = { path = "../../parsing/compiler" }