
rust_binary(
    name = "nordic_radio_dongle"
)

rust_binary(
    name = "nordic_bootloader"
)

rust_binary(
    name = "nordic"
)

rust_binary(
    name = "nordic_blink"
)

proto_data(
    name = "nrf52840",
    src = "nrf52840.textproto"
)

proto_data(
    name = "nrf52840_bootloader",
    src = "nrf52840_bootloader.textproto"
)

proto_data(
    name = "nrf52833",
    src = "nrf52833.textproto"
)

proto_data(
    name = "nrf52833_bootloader",
    src = "nrf52833_bootloader.textproto"
)
