
rust_binary(
    name = "nordic_radio_dongle"
)

rust_binary(
    name = "nordic_radio_serial"
)

rust_binary(
    name = "nordic_sensor"
)

rust_binary(
    name = "nordic_bootloader"
)

rust_binary(
    name = "nordic"
)

rust_binary(
    name = "nordic_blink"
)

rust_binary(
    name = "nordic_keyboard"
)

proto_data(
    name = "nrf52840",
    src = "nrf52840.textproto"
)

proto_data(
    name = "nrf52840_soft",
    src = "nrf52840_soft.textproto"
)

proto_data(
    name = "nrf52840_voron0_main",
    src = "nrf52840_voron0_main.textproto"
)

proto_data(
    name = "nrf52840_voron0_tool",
    src = "nrf52840_voron0_tool.textproto"
)

proto_data(
    name = "nrf52840_voron0_aux",
    src = "nrf52840_voron0_aux.textproto"
)

proto_data(
    name = "nrf52840_magnet_sensor",
    src = "nrf52840_magnet_sensor.textproto"
)

proto_data(
    name = "nrf52840_jbod_management",
    src = "nrf52840_jbod_management.textproto"
)

proto_data(
    name = "nrf52840_bootloader",
    src = "nrf52840_bootloader.textproto"
)

proto_data(
    name = "nrf52833",
    src = "nrf52833.textproto"
)

proto_data(
    name = "nrf52833_bootloader",
    src = "nrf52833_bootloader.textproto"
)
