[package]
name = "nordic"
version = "0.1.0"
authors = ["Dennis Shtatnov <densht@gmail.com>"]
edition = "2018"

[dependencies]
executor = { path = "../executor", default-features = false }
peripherals = { path = "../peripherals", default-features = false }
