# proto-file: pkg/builder/proto/config.proto
# proto-message: BuildConfig

platform {
    os: UNKNOWN
    architecture: UNKNOWN
}
rule_defaults {
    [type.googleapis.com/builder.RustBinaryAttrs] {
        compiler: CARGO
        profile: "release"
        no_default_features: true
        target: "thumbv7em-none-eabihf"
        rustflags: "-C link-arg=-Tpkg/nordic/link_33.x"
        cfg: ['target_label="nrf52833"', 'target_label="cortex_m"']
    }
}
