[package]
name = "crypto"
version = "0.1.0"
authors = ["Dennis Shtatnov <densht@gmail.com>"]
edition = "2018"

[dependencies]
macros = { path = "../macros" }
asn = { path = "../asn" }
math = { path = "../math" }
arrayref = "0.3.5"
common = { path = "../common" }
parsing = { path = "../parsing" }
pkix = { path = "../../third_party/pkix" }
bytes = { git = "https://github.com/tokio-rs/bytes" }
byteorder = "1.3.2"
hex = "0.3.2"
async-std = "0.99.4"
futures-preview = "0.3.0-alpha.17"
async-trait = "0.1.13"
generic-array = "0.13.2"
typenum = "1.11.2"
lazy_static = "1.4.0"
base64 = "0.11.0"
chrono = "0.4.9"