[package]
name = "crypto"
version = "0.1.0"
authors = ["Dennis Shtatnov <densht@gmail.com>"]
edition = "2018"

[lib]
doctest = false

[dependencies]
macros = { path = "../macros", optional = true }
asn = { path = "../asn", optional = true }
math = { path = "../math", optional = true }
common = { path = "../common", optional = true }
parsing = { path = "../parsing", optional = true }
pkix = { path = "../../third_party/pkix", optional = true }
byteorder = { version = "1.3.2", optional = true }
generic-array = { version = "0.13.2"}
typenum = { version = "1.11.2" }
lazy_static = { version = "1.4.0", optional = true }
chrono = { version = "0.4.9", optional = true }
async-std = { version = "1.9.0", optional = true }
arrayref = "0.3.5"

[dev-dependencies]
openssl = { path = "../../third_party/openssl" }

[features]
default = ["std"]
std = ["macros", "asn", "math", "common", "parsing", "pkix", "byteorder", "lazy_static", "chrono", "async-std"]