[package]
name = "crypto"
version = "0.1.0"
authors = ["Dennis Shtatnov <densht@gmail.com>"]
edition = "2018"

[dependencies]
macros = { path = "../macros" }
asn = { path = "../asn" }
math = { path = "../math" }
arrayref = "0.3.5"
common = { path = "../common" }
parsing = { path = "../parsing" }
pkix = { path = "../../third_party/pkix" }
byteorder = "1.3.2"
generic-array = "0.13.2"
typenum = "1.11.2"
lazy_static = "1.4.0"
chrono = "0.4.9"

[dev-dependencies]
openssl = { path = "../../third_party/openssl" }