[package]
name = "crypto"
version = "0.1.0"
authors = ["Dennis Shtatnov <densht@gmail.com>"]
edition = "2018"

[dependencies]
arrayref = "0.3.5"
common = { path = "../common" }
parsing = { path = "../parsing" }
bytes = { git = "https://github.com/tokio-rs/bytes" }
byteorder = "1.3.2"
hex = "0.3.2"