[package]
name = "executor"
version = "0.1.0"
edition = "2021"

[dependencies]
base_error = { path = "../base/error", default-features = false }
base_algorithms = { path = "../base/algorithms", default-features = false }
common = { path = "../common", default-features = false }
peripherals_raw = { path = "../peripherals/raw", default-features = false }
macros = { path = "../macros" }
failure = { version = "0.1.8", optional = true }
async-lock = { version = "3.4.2", optional = true }
async-channel = { version = "2.3.0", optional = true }
pin-project-lite = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
sys = { path = "../sys" }

[target.'cfg(not(target_os = "linux"))'.dependencies]
mio = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { workspace = true }  

[features]
default = ["std", "alloc"]
alloc = ["common/alloc", "base_error/alloc", "base_algorithms/alloc", "peripherals_raw/alloc"]
std = ["common/std", "base_error/std", "base_algorithms/std", "failure", "peripherals_raw/std", "async-lock", "async-channel"]