[package]
name = "executor"
version = "0.1.0"
authors = ["Dennis Shtatnov <densht@gmail.com>"]
edition = "2021"

[dependencies]
peripherals_raw = { path = "../peripherals_raw" }

[features]
default = ["std", "alloc"]
alloc = []
std = []