name: "ptp_follower"

replicas: 2

scheduling {
    distinct_nodes: true
    labels {
        label {
            key: "testcam"
            value: "yes"
        }
    }
}

worker {
    cwd: "/volumes/bundle"
    args: [
        "/volumes/bundle/built/pkg/net/ptp/ptp_service",
        "--mode=follower",
        "--iface=eth0",
        "--rpc_port=rpc",
        "--ptp_port=ptp"
    ]

    volumes: [
        {
            name: "bundle"
            build_target: "//pkg/net/ptp:ptp_service_bundle"
        }
    ]

    ports: [
        {
            name: "rpc"
            type: TCP
        },
        {
            name: "ptp"
            type: TCP  # TODO: Support UDP
            node_port: 319
        }
    ]

    additional_groups: ["ptp"]
    devices: [
        {
            source {
                raw: "/dev"
                limit: 1
            }
        }
    ]
}
