[package]
name = "cluster_client"
version = "0.1.0"
edition = "2018"

[dependencies]
common = { path = "../../common" }
base_radix = { path = "../../base/radix" }
base_algorithms = { path = "../../base/algorithms" }
crypto = { path = "../../crypto" }
protobuf = { path = "../../protobuf" }
db_table = { path = "../../db/table" }
http = { path = "../../http" }
http_util = { path = "../../http/util" }
macros = { path = "../../macros" }
db_txn_client = { path = "../../db/txn/client" }
db_txn_proto = { path = "../../db/txn/proto" }
rpc = { path = "../../rpc" }
rpc_util = { path = "../../rpc/util" }
net = { path = "../../net" }
web = { path = "../../web" }
raft_client = { path = "../../raft/client" }
protobuf_builtins = { path = "../../../third_party/protobuf_builtins" }
failure = "0.1.8"
executor = { path = "../../executor" }
executor_multitask = { path = "../../executor/multitask" }
file = { path = "../../file" }
sys = { path = "../../sys" }
cluster_proto = { path = "../proto" }
builder_proto = { path = "../../builder/proto" }
regexp_macros = { path = "../../automata/regexp_macros" }
automata = { path = "../../automata" }

# TODO: Make this test only.
db_txn = { path = "../../db/txn" }

[features]
default = ["std"]
std = ["alloc"]
alloc = []