[package]
name = "asn_compiler"
version = "0.1.0"
edition = "2018"

[dependencies]
common = { path = "../common" }
file = { path = "../file" }
parsing = { path = "../parsing" }
radix = { path = "../radix" }
