[package]
name = "usb_device"
version = "0.1.0"
edition = "2018"

[dependencies]
common = { path = "../common" }
usb = { path = "../usb" }
executor = { path = "../executor" }
macros = { path = "../macros" }