[package]
name = "mocap_proto"
version = "0.0.0"
edition = "2018"

[lib]
path = "lib.rs"

[dependencies]
common = { path = "../../../common" }
protobuf = { path = "../../../protobuf" }
macros = { path = "../../../macros" }
rpc = { path = "../../../rpc" }
media_camera_proto = { path = "../../../media/camera/proto" }
ptp_proto = { path = "../../../net/ptp/proto" }
math_proto = { path = "../../../math/proto" }
vision_proto = { path = "../../../vision/proto" }

[build-dependencies]
protobuf_compiler = { path = "../../../protobuf/compiler" }

[features]
default = ["std"]
std = ["alloc", "common/std", "protobuf/std"]
alloc = ["common/alloc", "protobuf/alloc"]
