syntax = "proto3";

package mocap;

import "pkg/vision/mocap/proto/camera.proto";
import "pkg/net/ptp/proto/service.proto";
import "pkg/media/camera/proto/property.proto";
import "pkg/vision/mocap/proto/matching.proto";
import "pkg/vision/mocap/proto/wand.proto";
import "pkg/vision/mocap/proto/rigid_body.proto";
import "pkg/vision/proto/params.proto";
import "pkg/vision/mocap/proto/checkerboard.proto";
import "pkg/vision/mocap/proto/wanding.proto";
import "pkg/vision/mocap/proto/simulation.proto";
import "pkg/vision/mocap/proto/skeleton.proto";

service Manager {
    // Gets the general state of the system.
    //
    // This changes at a low frequency and contains camera/system health
    // data and the current system configuration.
    rpc Status (MocapManagerStatusRequest) returns (MocapManagerStatus);

    // This reads the stream of syncronized sets of blobs from all cameras.
    //
    // So each 'ReadBlobsResponse' proto will be all the results from one timestamp
    // across all syncronized cameras.
    rpc ReadBlobs (ReadBlobsRequest) returns (stream ReadBlobsResponse);

    // This reads the stream of 3d points reconstructed from the 2d blobs.
    //
    // This will also include derived 3d data like rigid body state. These are
    // intentionally coupled with the 3d point data since the body trackers are
    // allowed to back propagate updates to the 3d data. 
    //
    // Note that for a given timestamp, this data will be available shortly after
    // the raw blobs data returned by 'ReadBlobs'.
    rpc ReadTrackedPoints (ReadTrackedPointsRequest) returns (stream ReadTrackedPointsResponse);

    // Reads the raw frames from a single camera.
    //
    // This has the same function as the mocap.Camera service's ReadFrames method
    // but will automatically deal with camera discovery and proxying to the camera. 
    rpc ReadFrames (ReadFramesRequest) returns (stream ReadFramesResponse);

    // Runs some command that mutates the state of the system.
    //
    // e.g. change camera controls, start wanding, define rigid bodies, etc.
    rpc Execute (ExecuteRequest) returns (ExecuteResponse);
}

message MocapManagerConfig {
    // Address of the job that contains all of the individual camera workers.
    //
    // TODO: This is not longer in use.
    string camera_service = 1;

    // Default config to send to all cameras (currently we assume that all cameras are similar)
    MocapCameraConfigureRequest initial_camera_config = 2;
    
    // Number of seconds since the first camera finishes processing a frame until we consider the
    // frame completed with all frames received so far.
    float frame_aggregation_timeout = 3;

    bool make_dummy_cameras = 4;

    repeated MocapPerCameraConfig per_camera = 5;

    BlobMatchingConfig matching = 6;

    WandPatternFinderConfig wand = 7;

    CheckerboardCalibrationConfig checkerboard = 8;

    WandingCalibrationConfig wanding = 9;

    RigidBodyTrackerConfig rigid_body_tracker = 10; 

    SkeletonTrackerConfig skeleton_tracker = 12;

    SphereProjectionFilter sphere_projection_filter = 13;

    AuxRpcServerConfig aux_rpc_server = 14;

    uint64 revision = 11;
}

message SphereProjectionFilter {
    double min_angle_check_radius_ratio = 1;
    
    double max_angle_error_degrees = 2;

    double max_normalized_radius_ratio = 3;
}

message MocapPerCameraConfig {
    string camera_id_str = 1;

    fixed64 camera_id = 2;

    vision.CameraIntrinsicsModelProto intrinsics = 3;

    vision.CameraExtrinsicsProto extrinsics = 4;

    optional bool enabled = 5;
}

message AuxRpcServerConfig {
    uint32 port = 1;

    // If true, the RPC server will attempt (once) to start when the
    // application first opens.
    bool autostart = 2;
}

message AuxRpcServerStatus {
    bool running = 1;

    // If set, there was an error while trying to start the server.
    string error = 2;
}


message MocapManagerStatusRequest {

}

message MocapManagerStatus {
    MocapManagerConfig config = 5;

    // List of all cameras that the manager has observed and can connect to.
    repeated MocapManagerCameraStatus cameras = 1;

    // Groups of one or more cameras.
    // 
    // Each camera belongs to exactly one group and every camera in a group
    // shares the same camera control configuration (e.g. same exposure
    // setting).
    repeated MocapCameraGroup groups = 2;

    // TODO: Eventually support differnt configs for different camera subsets.
    
    // Overall 'mode' of the system that determines how everything is operating.
    ManagerModeProto mode = 4;

    SingleCameraConfigOverride single_camera_override = 6;

    NetworkingStatus networking = 7;

    AuxRpcServerStatus aux_rpc_server = 8;

    reserved 3;
}

message NetworkingStatus {
    // Network interface name used for the cameras (if one was picked)
    string iface_name = 1;

    string iface_description = 2;

    bool healthy = 3;

    string error = 4;
}

message ManagerModeProto {
    oneof mode {
        bool off = 1;

        bool running = 2;

        // In this mode, a single camera is active and being calibrated using a checkerboard.
        //
        // For making this easier, the controls for all other cameras are locked and
        // changes to camera controls just effect the one camera being calibrated. 
        CheckerboardCalibrationState checkerboard_calibration = 3;

        WandingCalibrationState wanding_calibration = 4;

        RecordingState recording = 5;

        // playback
    }
}

message MocapCameraGroup {
    MocapCameraConfigureRequest config = 1;

    // Information about the connected sensor.
    // This data shouldn't change over time since we don't support camera hotswap.
    MocapCameraSensor sensor = 2;

    media.camera.Property camera_controls = 3;
}

message SingleCameraConfigOverride {
    fixed64 camera_id = 1;

    MocapCameraConfigureRequest config = 2;
}

message MocapManagerCameraStatus {
    fixed64 id = 1;

    // NOTE: To avoid excessive duplication, the configs are cleared in this
    MocapCameraStatus camera_status = 2;

    ptp.StatusResponse ptp_status = 3;

    // If true, this camera is being highlighted (with full blue LEDs).
    bool active = 4;

    // If true, we have goten at least one full camera_status and ptp_status.
    bool synced = 5;

    double last_sync_age = 6;

    // TODO: Metrics and health. Last heartbeat age 

    reserved 7, 8;
}

message ReadTrackedPointsRequest {
    // Max number of responses to return per second.
    // (leave unset for uncapped speed)
    uint32 max_rate = 1;
}

message ReadTrackedPointsResponse {
    uint64 frame_timestamp = 1;

    repeated TrackedPointProto points = 2;

    repeated RigidBodyProto rigid_bodies = 3;

    repeated SkeletonStateProto skeletons = 4;
}


message MocapManagerCameraMetrics {
    // Things like dropped frame count.

}

message ExecuteRequest {
    oneof command {
        ConfigureCamerasCommand configure_cameras = 1;

        // Makes a specific camera the active camera.
        // - The value of this field is the camera id
        // - This mainly makes it light up a different color.
        // - Selecting a camera deselects all other cameras.
        // - Id 0 will deselect all cameras.
        fixed64 select_camera = 2;

        StartCheckerboardCalibrationCommand start_checkerboard_calibration = 3;

        CancelCheckerboardCalibrationCommand cancel_checkerboard_calibration = 4;

        ProcessCheckerboardCalibrationCommand process_checkerboard_calibration = 5;

        ApplyCheckerboardCalibrationCommand apply_checkerboard_calibration = 6;

        bool capture_checkerboard_frame = 7;

        StartWandingCalibrationCommand start_wanding_calibration = 8;

        CancelWandingCalibrationCommand cancel_wanding_calibration = 9;

        ProcessWandingCalibrationCommand process_wanding_calibration = 10;

        ApplyWandingCalibrationCommand apply_wanding_calibration = 11;

        // Create a new rigid body or update and existing one with the given id.
        RigidBodyDefinition configure_rigid_body = 12;

        uint32 delete_rigid_body = 13;

        SimulationAnimationConfig configure_simulation = 14;

        SetOriginCommand set_origin = 15;

        SetCameraEnable set_camera_enabled = 16;

        StartRecordingCommand start_recording = 17;

        StopRecordingCommand stop_recording = 18;

        CreateSkeletonCommand create_skeleton = 19;

        DeleteSkeletonCommand delete_skeleton = 20;

        SetSkeletonSearchingCommand set_skeleton_searching = 21;

        bool start_aux_rpc_server = 22;

        bool stop_aux_rpc_server = 23;

        SaveFactoryIntrinsicsCommand save_factory_intrinsics = 24;
    }
}

message SaveFactoryIntrinsicsCommand {
    fixed64 camera_id = 1;
}

message SetCameraEnable {
    fixed64 camera_id = 1;

    // If true, this applies to all cameras and not just one.
    bool all_cameras = 2;

    bool enabled = 3;
}

message ExecuteResponse {

}

message ConfigureCamerasCommand {
    fixed64 camera_id = 1;

    fixed64 group_id = 2;

    MocapCameraConfigureRequest config = 3;
}

message SetOriginCommand {

}

message StartRecordingCommand {
    bool record_2d = 1;

    bool record_3d = 2;
}

message StopRecordingCommand {

}

message RecordingState {
    double elapsed_seconds = 1;

    bool error = 2;
}

// TODO: Get rid of this.
message MocapTrackingLog {
    // TODO: This doesn't really change so better to move somewhere else?
    repeated MocapTrackedCamera cameras = 1;

    repeated MocapTrackingState entries = 2;

    repeated SkeletonProto skeletons = 3;

    RigidBodyTrackerConfig rigid_body_tracker = 4; 
}

// TODO: Get rid of this.
message MocapTrackingState {

    repeated TrackedPointProto points = 2;

    repeated MocapTrackedLink links = 3;

    repeated SkeletonStateProto skeletons = 4;

    repeated RigidBodyProto rigid_bodies = 5;

    reserved 1;
}

// TODO: Get rid of this.
message MocapTrackedCamera {
    fixed64 id = 1;

    repeated double translation = 2;

    repeated double rotation = 3;
}


// TODO: Get rid of this.
message MocapTrackedLink {
    fixed64 point1_id = 1;
    fixed64 point2_id = 2;
}
