syntax = "proto3";

import "pkg/vision/mocap/proto/camera.proto";

package mocap;

service Supervisor {
    rpc Status (SupervisorStatusRequest) returns (SupervisorStatusResponse);

    // Runs a bash command and returns the output of the output.
    rpc Run (SupervisorRunRequest) returns (SupervisorRunResponse);

    rpc ReadFile (SupervisorReadFileRequest) returns (stream SupervisorReadFileResponse);

    // Performs an update of the camera.
    //
    // This RPC captures a sequence of steps to perform which should start with a 
    // 'start_update' command, followed by some operations and finally a 'commit_update'.
    //
    // Until 'commit_update' is sent, all commands before that are simply enqueued for
    // execution.
    //
    // - One response will be sent per request.
    // - At most one 'Update' RPC can be active on the server at a time.
    rpc Update (stream UpdateRequest) returns (stream UpdateResponse);
}

message SupervisorStatusRequest {

}

message SupervisorStatusResponse {

    CameraHardwareConfig hardware_config = 1;

    // TODO: Stuff like which version is currently installed
}

message UpdateRequest {
    oneof command {
        StartUpdateCommand start_update = 1;

        bytes payload_chunk = 2;

        bool install_deb = 3;

        CommitImageCommand install_image = 4;

        WriteFileCommand write_file = 5;

        CommitUpdateCommand commit_update = 6;
    }
}

message StartUpdateCommand {

}

message CommitImageCommand {
    // string image_id = 1;    
}

message WriteFileCommand {
    string path = 1;
}

message CommitUpdateCommand {

}

message UpdateResponse {
    bool commited = 1;

    float commit_progress = 2;
}


message SupervisorRunRequest {
    string command = 1;
}

message SupervisorRunResponse {
    bytes stdout = 1;
    bytes stderr = 2;
    bool success = 3;
}

message SupervisorReadFileRequest {
    string path = 1;
}

message SupervisorReadFileResponse {
    bytes data = 1;
}
