syntax = "proto3";

package mocap;


message WandPatternFinderConfig {
    // Maximum distance in pixels between two blobs in the pattern.
    double max_blob_center_pixel_distance = 1;

    // Maximum percentage difference between the radius of the smallest
    // and largest blob in the pattern.
    double max_radius_ratio = 2;

    double left_arm_length = 3;

    double right_arm_length = 4;

    double bottom_length = 5;

    double max_projection_stretch = 6;

    double max_reprojection_error = 7;

    // How high the points (sphere centers) are above the ground if the wand
    // is laying flat.
    double height = 8;
}
