
/*
This file was generated by giving the following prompt to Gemini 2.5 Pro along with the TMC2209 datasheet rev 1.09

```
Attached is a PDF which is the datasheet for the TMC2209 IC. Starting on the page labeled 22 (Section 5), there is a register map describing the memory of the IC. Convert the tables to corresponding Rust structs using the following partial example for the 'GCONF' register (internally represent each register as a u32 regardless of whether it uses fewer bytes):

```
/// GCONF – Global configuration flags
/// (R/W) Addr: 0x00
#[repr(transparent)]
#[derive(Clone, Copy, Debug)]
pub struct GCONF {
    raw: u32
}

impl Register for GCONF {
    fn addr() -> u8 { 0x00 } // From the 'Addr' column in the datasheet
    fn from_raw(value: u32) -> Self { Self { raw: value } }
    fn to_raw(&self) -> u32 { self.raw }
}

impl GCONF {


    /// internal_Rsense (Reset default: OTP)
    ///
    /// 0: Operation with external sense resistors
    /// 1: Internal sense resistors. Use current supplied into
    ///    VREF as reference for internal sense resistor. VREF
    ///    pin internally is driven to GND in this mode.
    pub fn internal_rsense(&self) -> u8 {
        get_bit_field(self.raw, 1, 1) as u8
    }

    pub fn set_internal_rsense(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 1, 1, v as u32);
    }

    // TODO: Add getters/setters for all other mentioned bit fields.
}
```

Do not wrap the code in a Rust module. Do not derive Default for any of the structs. Do not include any citation markers back to the original file.

Assume that the following code already exists to simply the code:

```
pub trait Register {
    fn addr() -> u8;
}

#[inline(always)]
pub const fn get_bit_field(v: u32, shift: usize, width: usize) -> u32 {
    let mask = (1 << width) - 1;
    (v >> shift) & mask
}

#[inline(always)]
pub const fn set_bit_field(v: u32, shift: usize, width: usize, field: u32) -> u32 {
    let mask = !(((1 << width) - 1) << shift);
    (v & mask) | (field << shift)
}
```


```
*/

use base_util::bit_field::*;

use crate::tmc2209::utils::*;


/// GCONF – Global configuration flags
/// (R/W) Addr: 0x00
#[repr(transparent)]
#[derive(Clone, Copy, Debug)]
pub struct GCONF {
    raw: u32
}

impl Register for GCONF {
    fn addr() -> u8 { 0x00 }
    fn from_raw(value: u32) -> Self { Self { raw: value } }
    fn to_raw(&self) -> u32 { self.raw }
}

impl GCONF {
    /// I_scale_analog (Reset default=1)
    ///
    /// 0: Use internal reference derived from 5VOUT
    /// 1: Use voltage supplied to VREF as current reference
    pub fn i_scale_analog(&self) -> u8 {
        get_bit_field(self.raw, 0, 1) as u8
    }

    pub fn set_i_scale_analog(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 0, 1, v as u32);
        self
    }

    /// internal_Rsense (Reset default: OTP)
    ///
    /// 0: Operation with external sense resistors
    /// 1: Internal sense resistors. Use current supplied into
    ///    VREF as reference for internal sense resistor. VREF
    ///    pin internally is driven to GND in this mode.
    pub fn internal_rsense(&self) -> u8 {
        get_bit_field(self.raw, 1, 1) as u8
    }

    pub fn set_internal_rsense(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 1, 1, v as u32);
        self
    }

    /// en_SpreadCycle (Reset default: OTP)
    ///
    /// 0: StealthChop PWM mode enabled (depending on
    ///    velocity thresholds).
    /// 1: SpreadCycle mode enabled
    pub fn en_spreadcycle(&self) -> u8 {
        get_bit_field(self.raw, 2, 1) as u8
    }

    pub fn set_en_spreadcycle(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 2, 1, v as u32);
        self
    }

    /// shaft
    ///
    /// 0: Normal motor direction
    /// 1: Inverse motor direction
    pub fn shaft(&self) -> u8 {
        get_bit_field(self.raw, 3, 1) as u8
    }

    pub fn set_shaft(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 3, 1, v as u32);
        self
    }

    /// index_otpw
    ///
    /// 0: INDEX shows the first microstep position of
    ///    sequencer
    /// 1: INDEX pin outputs overtemperature prewarning
    ///    flag (otpw) instead
    pub fn index_otpw(&self) -> u8 {
        get_bit_field(self.raw, 4, 1) as u8
    }

    pub fn set_index_otpw(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 4, 1, v as u32);
        self
    }

    /// index_step
    ///
    /// 0: INDEX output as selected by index_otpw
    /// 1: INDEX output shows step pulses from internal
    ///    pulse generator (toggle upon each step)
    pub fn index_step(&self) -> u8 {
        get_bit_field(self.raw, 5, 1) as u8
    }

    pub fn set_index_step(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 5, 1, v as u32);
        self
    }

    /// pdn_disable
    ///
    /// 0: PDN_UART controls standstill current reduction
    /// 1: PDN_UART input function disabled. Set this bit,
    ///    when using the UART interface!
    pub fn pdn_disable(&self) -> u8 {
        get_bit_field(self.raw, 6, 1) as u8
    }

    pub fn set_pdn_disable(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 6, 1, v as u32);
        self
    }

    /// mstep_reg_select
    ///
    /// 0: Microstep resolution selected by pins MS1, MS2
    /// 1: Microstep resolution selected by MRES register
    pub fn mstep_reg_select(&self) -> u8 {
        get_bit_field(self.raw, 7, 1) as u8
    }

    pub fn set_mstep_reg_select(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 7, 1, v as u32);
        self
    }

    /// multistep_filt (Reset default=1)
    ///
    /// 0: No filtering of STEP pulses
    /// 1: Software pulse generator optimization enabled
    ///    when fullstep frequency > 750Hz (roughly). TSTEP
    ///    shows filtered step time values when active.
    pub fn multistep_filt(&self) -> u8 {
        get_bit_field(self.raw, 8, 1) as u8
    }

    pub fn set_multistep_filt(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 8, 1, v as u32);
        self
    }

    /// test_mode
    ///
    /// 0: Normal operation
    /// 1: Enable analog test output on pin ENN
    ///    Attention: Not for user, set to 0 for normal operation!
    pub fn test_mode(&self) -> u8 {
        get_bit_field(self.raw, 9, 1) as u8
    }

    pub fn set_test_mode(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 9, 1, v as u32);
        self
    }
}

/// GSTAT – Global status flags
/// (R+WC) Addr: 0x01
#[repr(transparent)]
#[derive(Clone, Copy, Debug)]
pub struct GSTAT {
    raw: u32
}

impl Register for GSTAT {
    fn addr() -> u8 { 0x01 }
    fn from_raw(value: u32) -> Self { Self { raw: value } }
    fn to_raw(&self) -> u32 { self.raw }
}

impl GSTAT {
    /// reset
    ///
    /// 1: Indicates that the IC has been reset since the last
    ///    read access to GSTAT. (Write '1' to clear)
    pub fn reset(&self) -> u8 {
        get_bit_field(self.raw, 0, 1) as u8
    }

    pub fn set_reset(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 0, 1, v as u32);
        self
    }

    /// drv_err
    ///
    /// 1: Indicates, that the driver has been shut down due
    ///    to overtemperature or short circuit detection. (Write '1' to clear)
    pub fn drv_err(&self) -> u8 {
        get_bit_field(self.raw, 1, 1) as u8
    }

    pub fn set_drv_err(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 1, 1, v as u32);
        self
    }

    /// uv_cp
    ///
    /// 1: Indicates an undervoltage on the charge pump.
    ///    The driver is disabled in this case. (Write '1' to clear)
    pub fn uv_cp(&self) -> u8 {
        get_bit_field(self.raw, 2, 1) as u8
    }

    pub fn set_uv_cp(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 2, 1, v as u32);
        self
    }
}

/// IFCNT – Interface transmission counter
/// (R) Addr: 0x02
#[repr(transparent)]
#[derive(Clone, Copy, Debug)]
pub struct IFCNT {
    raw: u32
}

impl Register for IFCNT {
    fn addr() -> u8 { 0x02 }
    fn from_raw(value: u32) -> Self { Self { raw: value } }
    fn to_raw(&self) -> u32 { self.raw }
}

impl IFCNT {
    /// Interface transmission counter. This register becomes
    /// incremented with each successful UART interface write
    /// access.
    pub fn ifcnt(&self) -> u8 {
        get_bit_field(self.raw, 0, 8) as u8
    }
}

/// NODECONF – UART extended address
/// (W) Addr: 0x03
#[repr(transparent)]
#[derive(Clone, Copy, Debug)]
pub struct NODECONF {
    raw: u32
}

impl Register for NODECONF {
    fn addr() -> u8 { 0x03 }
    fn from_raw(value: u32) -> Self { Self { raw: value } }
    fn to_raw(&self) -> u32 { self.raw }
}

impl NODECONF {
    /// SENDDELAY for read access (time until reply is sent):
    /// 0, 1: 8 bit times
    /// 2, 3: 3*8 bit times
    /// ...
    /// 14, 15: 15*8 bit times
    pub fn senddelay(&self) -> u8 {
        get_bit_field(self.raw, 8, 4) as u8
    }

    pub fn set_senddelay(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 8, 4, v as u32);
        self
    }
}

/// OTP_PROG – OTP programming
/// (W) Addr: 0x04
#[repr(transparent)]
#[derive(Clone, Copy, Debug)]
pub struct OTP_PROG {
    raw: u32
}

impl Register for OTP_PROG {
    fn addr() -> u8 { 0x04 }
    fn from_raw(value: u32) -> Self { Self { raw: value } }
    fn to_raw(&self) -> u32 { self.raw }
}

impl OTP_PROG {
    /// OTPBIT
    /// Selection of OTP bit to be programmed (n=0..7 programs bit n)
    pub fn otpbit(&self) -> u8 {
        get_bit_field(self.raw, 0, 3) as u8
    }

    pub fn set_otpbit(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 0, 3, v as u32);
        self
    }

    /// OTPBYTE
    /// Selection of OTP programming location (0, 1 or 2)
    pub fn otpbyte(&self) -> u8 {
        get_bit_field(self.raw, 4, 2) as u8
    }

    pub fn set_otpbyte(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 4, 2, v as u32);
        self
    }

    /// OTPMAGIC
    /// Set to 0xbd to enable programming.
    pub fn otpmagic(&self) -> u8 {
        get_bit_field(self.raw, 8, 8) as u8
    }

    pub fn set_otpmagic(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 8, 8, v as u32);
        self
    }
}

/// OTP_READ – OTP memory access
/// (R) Addr: 0x05
#[repr(transparent)]
#[derive(Clone, Copy, Debug)]
pub struct OTP_READ {
    raw: u32
}

impl Register for OTP_READ {
    fn addr() -> u8 { 0x05 }
    fn from_raw(value: u32) -> Self { Self { raw: value } }
    fn to_raw(&self) -> u32 { self.raw }
}

impl OTP_READ {
    /// OTP0 byte 0 read data
    pub fn otp0(&self) -> u8 {
        get_bit_field(self.raw, 0, 8) as u8
    }

    /// OTP1 byte 1 read data
    pub fn otp1(&self) -> u8 {
        get_bit_field(self.raw, 8, 8) as u8
    }

    /// OTP2 byte 2 read data
    pub fn otp2(&self) -> u8 {
        get_bit_field(self.raw, 16, 8) as u8
    }
}

/// IOIN – Input pin status
/// (R) Addr: 0x06
#[repr(transparent)]
#[derive(Clone, Copy, Debug)]
pub struct IOIN {
    raw: u32
}

impl Register for IOIN {
    fn addr() -> u8 { 0x06 }
    fn from_raw(value: u32) -> Self { Self { raw: value } }
    fn to_raw(&self) -> u32 { self.raw }
}

impl IOIN {
    /// ENN input pin state
    pub fn enn(&self) -> u8 {
        get_bit_field(self.raw, 0, 1) as u8
    }

    /// MS1 input pin state
    pub fn ms1(&self) -> u8 {
        get_bit_field(self.raw, 2, 1) as u8
    }

    /// MS2 input pin state
    pub fn ms2(&self) -> u8 {
        get_bit_field(self.raw, 3, 1) as u8
    }

    /// DIAG input pin state
    pub fn diag(&self) -> u8 {
        get_bit_field(self.raw, 4, 1) as u8
    }

    /// PDN_UART input pin state
    pub fn pdn_uart(&self) -> u8 {
        get_bit_field(self.raw, 6, 1) as u8
    }

    /// STEP input pin state
    pub fn step(&self) -> u8 {
        get_bit_field(self.raw, 7, 1) as u8
    }

    /// SPREAD_EN input pin state
    pub fn spread_en(&self) -> u8 {
        get_bit_field(self.raw, 8, 1) as u8
    }

    /// DIR input pin state
    pub fn dir(&self) -> u8 {
        get_bit_field(self.raw, 9, 1) as u8
    }

    /// VERSION
    /// 0x21: first version of the IC
    pub fn version(&self) -> u8 {
        get_bit_field(self.raw, 24, 8) as u8
    }
}

/// FACTORY_CONF – Factory configuration
/// (R/W) Addr: 0x07
#[repr(transparent)]
#[derive(Clone, Copy, Debug)]
pub struct FACTORY_CONF {
    raw: u32
}

impl Register for FACTORY_CONF {
    fn addr() -> u8 { 0x07 }
    fn from_raw(value: u32) -> Self { Self { raw: value } }
    fn to_raw(&self) -> u32 { self.raw }
}

impl FACTORY_CONF {
    /// FCLKTRIM (Reset default: OTP)
    /// 0...31: Lowest to highest clock frequency.
    pub fn fclktrim(&self) -> u8 {
        get_bit_field(self.raw, 0, 5) as u8
    }

    pub fn set_fclktrim(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 0, 5, v as u32);
        self
    }

    /// OTTRIM (Default: OTP)
    /// %00: OT=143°C, OTPW=120°C
    /// %01: OT=150°C, OTPW=120°C
    /// %10: OT=150°C, OTPW=143°C
    /// %11: OT=157°C, OTPW=143°C
    pub fn ottrim(&self) -> u8 {
        get_bit_field(self.raw, 8, 2) as u8
    }

    pub fn set_ottrim(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 8, 2, v as u32);
        self
    }
}

/// IHOLD_IRUN – Driver current control
/// (W) Addr: 0x10
#[repr(transparent)]
#[derive(Clone, Copy, Debug)]
pub struct IHOLD_IRUN {
    raw: u32
}

impl Register for IHOLD_IRUN {
    fn addr() -> u8 { 0x10 }
    fn from_raw(value: u32) -> Self { Self { raw: value } }
    fn to_raw(&self) -> u32 { self.raw }
}

impl IHOLD_IRUN {
    /// IHOLD (Reset default: OTP)
    /// Standstill current (0=1/32...31=32/32)
    pub fn ihold(&self) -> u8 {
        get_bit_field(self.raw, 0, 5) as u8
    }

    pub fn set_ihold(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 0, 5, v as u32);
        self
    }

    /// IRUN (Reset default=31)
    /// Motor run current (0=1/32...31=32/32)
    pub fn irun(&self) -> u8 {
        get_bit_field(self.raw, 8, 5) as u8
    }

    pub fn set_irun(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 8, 5, v as u32);
        self
    }

    /// IHOLDDELAY (Reset default: OTP)
    /// Controls the number of clock cycles for motor power
    /// down after standstill is detected.
    /// 0: instant power down
    /// 1..15: Delay per current reduction step
    pub fn iholddelay(&self) -> u8 {
        get_bit_field(self.raw, 16, 4) as u8
    }

    pub fn set_iholddelay(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 16, 4, v as u32);
        self
    }
}

/// TPOWERDOWN – Standstill power down delay
/// (W) Addr: 0x11
#[repr(transparent)]
#[derive(Clone, Copy, Debug)]
pub struct TPOWERDOWN {
    raw: u32
}

impl Register for TPOWERDOWN {
    fn addr() -> u8 { 0x11 }
    fn from_raw(value: u32) -> Self { Self { raw: value } }
    fn to_raw(&self) -> u32 { self.raw }
}

impl TPOWERDOWN {
    /// TPOWERDOWN (Reset default=20)
    /// Sets the delay time from stand still (stst) detection to motor
    /// current power down. Time range is about 0 to 5.6 seconds.
    pub fn tpowerdown(&self) -> u8 {
        get_bit_field(self.raw, 0, 8) as u8
    }

    pub fn set_tpowerdown(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 0, 8, v as u32);
        self
    }
}

/// TSTEP – Measured time between two 1/256 microsteps
/// (R) Addr: 0x12
#[repr(transparent)]
#[derive(Clone, Copy, Debug)]
pub struct TSTEP {
    raw: u32
}

impl Register for TSTEP {
    fn addr() -> u8 { 0x12 }
    fn from_raw(value: u32) -> Self { Self { raw: value } }
    fn to_raw(&self) -> u32 { self.raw }
}

impl TSTEP {
    /// Actual measured time between two 1/256 microsteps
    /// in units of 1/fCLK.
    pub fn tstep(&self) -> u32 {
        get_bit_field(self.raw, 0, 20)
    }
}

/// TPWMTHRS – Velocity threshold for StealthChop voltage PWM mode
/// (W) Addr: 0x13
#[repr(transparent)]
#[derive(Clone, Copy, Debug)]
pub struct TPWMTHRS {
    raw: u32
}

impl Register for TPWMTHRS {
    fn addr() -> u8 { 0x13 }
    fn from_raw(value: u32) -> Self { Self { raw: value } }
    fn to_raw(&self) -> u32 { self.raw }
}

impl TPWMTHRS {
    /// Sets the upper velocity for StealthChop voltage PWM mode.
    /// When TSTEP < TPWMTHRS, the driver switches to SpreadCycle.
    /// 0: Disabled
    pub fn tpwmthrs(&self) -> u32 {
        get_bit_field(self.raw, 0, 20)
    }

    pub fn set_tpwmthrs(&mut self, v: u32) -> &mut Self {
        self.raw = set_bit_field(self.raw, 0, 20, v);
        self
    }
}

/// TCOOLTHRS – Lower velocity threshold for CoolStep/StallGuard
/// (W) Addr: 0x14
#[repr(transparent)]
#[derive(Clone, Copy, Debug)]
pub struct TCOOLTHRS {
    raw: u32
}

impl Register for TCOOLTHRS {
    fn addr() -> u8 { 0x14 }
    fn from_raw(value: u32) -> Self { Self { raw: value } }
    fn to_raw(&self) -> u32 { self.raw }
}

impl TCOOLTHRS {
    /// This is the lower threshold velocity for switching on smart
    /// energy CoolStep and StallGuard to DIAG output.
    /// (TCOOLTHRS <= TSTEP)
    pub fn tcoolthrs(&self) -> u32 {
        get_bit_field(self.raw, 0, 20)
    }

    pub fn set_tcoolthrs(&mut self, v: u32) -> &mut Self {
        self.raw = set_bit_field(self.raw, 0, 20, v);
        self
    }
}

/// VACTUAL – Motor velocity
/// (W) Addr: 0x22
#[repr(transparent)]
#[derive(Clone, Copy, Debug)]
pub struct VACTUAL {
    raw: u32
}

impl Register for VACTUAL {
    fn addr() -> u8 { 0x22 }
    fn from_raw(value: u32) -> Self { Self { raw: value } }
    fn to_raw(&self) -> u32 { self.raw }
}

impl VACTUAL {
    /// VACTUAL allows moving the motor by UART control.
    /// It gives the motor velocity in +-(2^23)-1 [µsteps / t]
    /// 0: Normal operation (STEP input)
    /// +/-0: Motor moves with the velocity given by VACTUAL.
    pub fn vactual(&self) -> u32 {
        get_bit_field(self.raw, 0, 24)
    }

    pub fn set_vactual(&mut self, v: u32) -> &mut Self {
        self.raw = set_bit_field(self.raw, 0, 24, v);
        self
    }
}

/// SGTHRS – StallGuard detection threshold
/// (W) Addr: 0x40
#[repr(transparent)]
#[derive(Clone, Copy, Debug)]
pub struct SGTHRS {
    raw: u32
}

impl Register for SGTHRS {
    fn addr() -> u8 { 0x40 }
    fn from_raw(value: u32) -> Self { Self { raw: value } }
    fn to_raw(&self) -> u32 { self.raw }
}

impl SGTHRS {
    /// Detection threshold for stall. The StallGuard value SG_RESULT
    /// becomes compared to the double of this threshold.
    /// A stall is signaled with SG_RESULT <= SGTHRS*2
    pub fn sgthrs(&self) -> u8 {
        get_bit_field(self.raw, 0, 8) as u8
    }

    pub fn set_sgthrs(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 0, 8, v as u32);
        self
    }
}

/// SG_RESULT – StallGuard result
/// (R) Addr: 0x41
#[repr(transparent)]
#[derive(Clone, Copy, Debug)]
pub struct SG_RESULT {
    raw: u32
}

impl Register for SG_RESULT {
    fn addr() -> u8 { 0x41 }
    fn from_raw(value: u32) -> Self { Self { raw: value } }
    fn to_raw(&self) -> u32 { self.raw }
}

impl SG_RESULT {
    /// StallGuard result. A higher value signals a lower
    /// motor load and more torque headroom.
    pub fn sg_result(&self) -> u16 {
        get_bit_field(self.raw, 0, 10) as u16
    }
}

/// COOLCONF – CoolStep configuration
/// (W) Addr: 0x42
#[repr(transparent)]
#[derive(Clone, Copy, Debug)]
pub struct COOLCONF {
    raw: u32
}

impl Register for COOLCONF {
    fn addr() -> u8 { 0x42 }
    fn from_raw(value: u32) -> Self { Self { raw: value } }
    fn to_raw(&self) -> u32 { self.raw }
}

impl COOLCONF {
    /// semin
    /// minimum StallGuard value for smart current control
    /// 0: smart current control CoolStep off
    /// 1...15: 1...15
    pub fn semin(&self) -> u8 {
        get_bit_field(self.raw, 0, 4) as u8
    }

    pub fn set_semin(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 0, 4, v as u32);
        self
    }

    /// seup
    /// current up step width
    /// %00...%11: 1, 2, 4, 8
    pub fn seup(&self) -> u8 {
        get_bit_field(self.raw, 5, 2) as u8
    }

    pub fn set_seup(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 5, 2, v as u32);
        self
    }

    /// semax
    /// StallGuard hysteresis value for smart current control
    /// %0000...%1111: 0...15
    pub fn semax(&self) -> u8 {
        get_bit_field(self.raw, 8, 4) as u8
    }

    pub fn set_semax(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 8, 4, v as u32);
        self
    }

    /// sedn
    /// current down step speed
    /// %00: For each 32 StallGuard4 values decrease by one
    /// %01: For each 8 StallGuard4 values decrease by one
    /// %10: For each 2 StallGuard4 values decrease by one
    /// %11: For each StallGuard4 value decrease by one
    pub fn sedn(&self) -> u8 {
        get_bit_field(self.raw, 13, 2) as u8
    }

    pub fn set_sedn(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 13, 2, v as u32);
        self
    }

    /// seimin
    /// minimum current for smart current control
    /// 0: 1/2 of current setting (IRUN)
    /// 1: 1/4 of current setting (IRUN)
    pub fn seimin(&self) -> u8 {
        get_bit_field(self.raw, 15, 1) as u8
    }

    pub fn set_seimin(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 15, 1, v as u32);
        self
    }
}

/// MSCNT – Microstep counter
/// (R) Addr: 0x6A
#[repr(transparent)]
#[derive(Clone, Copy, Debug)]
pub struct MSCNT {
    raw: u32
}

impl Register for MSCNT {
    fn addr() -> u8 { 0x6A }
    fn from_raw(value: u32) -> Self { Self { raw: value } }
    fn to_raw(&self) -> u32 { self.raw }
}

impl MSCNT {
    /// Microstep counter. Indicates actual position in
    /// the microstep table for CUR_A. (0..1023)
    pub fn mscnt(&self) -> u16 {
        get_bit_field(self.raw, 0, 10) as u16
    }
}

/// MSCURACT – Microstep actual current
/// (R) Addr: 0x6B
#[repr(transparent)]
#[derive(Clone, Copy, Debug)]
pub struct MSCURACT {
    raw: u32
}

impl Register for MSCURACT {
    fn addr() -> u8 { 0x6B }
    fn from_raw(value: u32) -> Self { Self { raw: value } }
    fn to_raw(&self) -> u32 { self.raw }
}

impl MSCURACT {
    /// CUR_B (signed):
    /// Actual microstep current for motor phase B (sine wave)
    pub fn cur_b(&self) -> u16 {
        get_bit_field(self.raw, 0, 9) as u16
    }

    /// CUR_A (signed):
    /// Actual microstep current for motor phase A (co-sine wave)
    pub fn cur_a(&self) -> u16 {
        get_bit_field(self.raw, 16, 9) as u16
    }
}

/// CHOPCONF – Chopper and driver configuration
/// (R/W) Addr: 0x6C
#[repr(transparent)]
#[derive(Clone, Copy, Debug)]
pub struct CHOPCONF {
    raw: u32
}

impl Register for CHOPCONF {
    fn addr() -> u8 { 0x6C }
    fn from_raw(value: u32) -> Self { Self { raw: value } }
    fn to_raw(&self) -> u32 { self.raw }
}

impl CHOPCONF {
    /// toff
    /// Off time setting controls duration of slow decay phase
    /// %0000: Driver disable
    /// %0001...%1111: 1...15
    pub fn toff(&self) -> u8 {
        get_bit_field(self.raw, 0, 4) as u8
    }

    pub fn set_toff(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 0, 4, v as u32);
        self
    }

    /// hstrt
    /// Hysteresis start value
    /// %000...%111: Add 1, 2, ..., 8 to hysteresis low value HEND
    pub fn hstrt(&self) -> u8 {
        get_bit_field(self.raw, 4, 3) as u8
    }

    pub fn set_hstrt(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 4, 3, v as u32);
        self
    }

    /// hend
    /// Hysteresis low value
    /// %0000...%1111: Hysteresis is -3, -2, -1, 0, 1, ..., 12
    pub fn hend(&self) -> u8 {
        get_bit_field(self.raw, 7, 4) as u8
    }

    pub fn set_hend(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 7, 4, v as u32);
        self
    }

    /// tbl
    /// blank time select
    /// %00...%11: Set comparator blank time to 16, 24, 32 or 40 clocks
    pub fn tbl(&self) -> u8 {
        get_bit_field(self.raw, 15, 2) as u8
    }

    pub fn set_tbl(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 15, 2, v as u32);
        self
    }

    /// vsense
    /// sense resistor voltage based current scaling
    /// 0: Low sensitivity, high sense resistor voltage
    /// 1: High sensitivity, low sense resistor voltage
    pub fn vsense(&self) -> u8 {
        get_bit_field(self.raw, 17, 1) as u8
    }

    pub fn set_vsense(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 17, 1, v as u32);
        self
    }

    /// mres
    /// micro step resolution
    /// %0000: Native 256 microstep setting
    /// %0001...%1000: 128, 64, 32, 16, 8, 4, 2, FULLSTEP
    pub fn mres(&self) -> u8 {
        get_bit_field(self.raw, 24, 4) as u8
    }

    pub fn set_mres(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 24, 4, v as u32);
        self
    }

    /// intpol
    /// interpolation to 256 microsteps
    /// 1: The actual microstep resolution (MRES) becomes
    ///    extrapolated to 256 microsteps. (Default: 1)
    pub fn intpol(&self) -> u8 {
        get_bit_field(self.raw, 28, 1) as u8
    }

    pub fn set_intpol(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 28, 1, v as u32);
        self
    }

    /// dedge
    /// enable double edge step pulses
    /// 1: Enable step impulse at each step edge.
    pub fn dedge(&self) -> u8 {
        get_bit_field(self.raw, 29, 1) as u8
    }

    pub fn set_dedge(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 29, 1, v as u32);
        self
    }

    /// diss2g
    /// short to GND protection disable
    /// 0: Short to GND protection is on
    /// 1: Short to GND protection is disabled
    pub fn diss2g(&self) -> u8 {
        get_bit_field(self.raw, 30, 1) as u8
    }

    pub fn set_diss2g(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 30, 1, v as u32);
        self
    }

    /// diss2vs
    /// Low side short protection disable
    /// 0: Short protection low side is on
    /// 1: Short protection low side is disabled
    pub fn diss2vs(&self) -> u8 {
        get_bit_field(self.raw, 31, 1) as u8
    }

    pub fn set_diss2vs(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 31, 1, v as u32);
        self
    }
}

/// DRV_STATUS – Driver status flags and current level
/// (R) Addr: 0x6F
#[repr(transparent)]
#[derive(Clone, Copy, Debug)]
pub struct DRV_STATUS {
    raw: u32
}

impl Register for DRV_STATUS {
    fn addr() -> u8 { 0x6F }
    fn from_raw(value: u32) -> Self { Self { raw: value } }
    fn to_raw(&self) -> u32 { self.raw }
}

impl DRV_STATUS {
    /// otpw
    /// overtemperature pre-warning flag
    pub fn otpw(&self) -> u8 {
        get_bit_field(self.raw, 0, 1) as u8
    }

    /// ot
    /// overtemperature flag
    pub fn ot(&self) -> u8 {
        get_bit_field(self.raw, 1, 1) as u8
    }

    /// s2ga
    /// short to ground indicator phase A
    pub fn s2ga(&self) -> u8 {
        get_bit_field(self.raw, 2, 1) as u8
    }

    /// s2gb
    /// short to ground indicator phase B
    pub fn s2gb(&self) -> u8 {
        get_bit_field(self.raw, 3, 1) as u8
    }

    /// s2vsa
    /// low side short indicator phase A
    pub fn s2vsa(&self) -> u8 {
        get_bit_field(self.raw, 4, 1) as u8
    }

    /// s2vsb
    /// low side short indicator phase B
    pub fn s2vsb(&self) -> u8 {
        get_bit_field(self.raw, 5, 1) as u8
    }

    /// ola
    /// open load indicator phase A
    pub fn ola(&self) -> u8 {
        get_bit_field(self.raw, 6, 1) as u8
    }

    /// olb
    /// open load indicator phase B
    pub fn olb(&self) -> u8 {
        get_bit_field(self.raw, 7, 1) as u8
    }

    /// t120
    /// 120°C comparator
    pub fn t120(&self) -> u8 {
        get_bit_field(self.raw, 8, 1) as u8
    }

    /// t143
    /// 143°C comparator
    pub fn t143(&self) -> u8 {
        get_bit_field(self.raw, 9, 1) as u8
    }

    /// t150
    /// 150°C comparator
    pub fn t150(&self) -> u8 {
        get_bit_field(self.raw, 10, 1) as u8
    }

    /// t157
    /// 157°C comparator
    pub fn t157(&self) -> u8 {
        get_bit_field(self.raw, 11, 1) as u8
    }

    /// CS_ACTUAL
    /// Actual current control scaling
    pub fn cs_actual(&self) -> u8 {
        get_bit_field(self.raw, 16, 5) as u8
    }

    /// stealth
    /// StealthChop indicator
    /// 1: Driver operates in StealthChop mode
    /// 0: Driver operates in SpreadCycle mode
    pub fn stealth(&self) -> u8 {
        get_bit_field(self.raw, 30, 1) as u8
    }

    /// stst
    /// standstill indicator
    pub fn stst(&self) -> u8 {
        get_bit_field(self.raw, 31, 1) as u8
    }
}

/// PWMCONF – StealthChop PWM chopper configuration
/// (R/W) Addr: 0x70
#[repr(transparent)]
#[derive(Clone, Copy, Debug)]
pub struct PWMCONF {
    raw: u32
}

impl Register for PWMCONF {
    fn addr() -> u8 { 0x70 }
    fn from_raw(value: u32) -> Self { Self { raw: value } }
    fn to_raw(&self) -> u32 { self.raw }
}

impl PWMCONF {
    /// PWM_OFS
    /// User defined PWM amplitude offset (0-255)
    pub fn pwm_ofs(&self) -> u8 {
        get_bit_field(self.raw, 0, 8) as u8
    }

    pub fn set_pwm_ofs(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 0, 8, v as u32);
        self
    }

    /// PWM_GRAD
    /// User defined amplitude gradient
    pub fn pwm_grad(&self) -> u8 {
        get_bit_field(self.raw, 8, 8) as u8
    }

    pub fn set_pwm_grad(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 8, 8, v as u32);
        self
    }

    /// pwm_freq
    /// PWM frequency selection
    /// %00: fPWM = 2/1024 fCLK
    /// %01: fPWM = 2/683 fCLK
    /// %10: fPWM = 2/512 fCLK
    /// %11: fPWM = 2/410 fCLK
    pub fn pwm_freq(&self) -> u8 {
        get_bit_field(self.raw, 16, 2) as u8
    }

    pub fn set_pwm_freq(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 16, 2, v as u32);
        self
    }

    /// pwm_autoscale
    /// PWM automatic amplitude scaling
    /// 0: User defined feed forward PWM amplitude
    /// 1: Enable automatic current control (Reset default)
    pub fn pwm_autoscale(&self) -> u8 {
        get_bit_field(self.raw, 18, 1) as u8
    }

    pub fn set_pwm_autoscale(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 18, 1, v as u32);
        self
    }

    /// pwm_autograd
    /// PWM automatic gradient adaptation
    /// 0: Fixed value for PWM_GRAD
    /// 1: Automatic tuning
    pub fn pwm_autograd(&self) -> u8 {
        get_bit_field(self.raw, 19, 1) as u8
    }

    pub fn set_pwm_autograd(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 19, 1, v as u32);
        self
    }

    /// freewheel
    /// Stand still option when motor current setting is zero
    /// %00: Normal operation
    /// %01: Freewheeling
    /// %10: Coil shorted using LS drivers
    /// %11: Coil shorted using HS drivers
    pub fn freewheel(&self) -> u8 {
        get_bit_field(self.raw, 20, 2) as u8
    }

    pub fn set_freewheel(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 20, 2, v as u32);
        self
    }

    /// pwm_reg
    /// Regulation loop gradient
    /// %0001...%1111: 1...15
    pub fn pwm_reg(&self) -> u8 {
        get_bit_field(self.raw, 24, 4) as u8
    }

    pub fn set_pwm_reg(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 24, 4, v as u32);
        self
    }

    /// pwm_lim
    /// PWM automatic scale amplitude limit when switching on
    pub fn pwm_lim(&self) -> u8 {
        get_bit_field(self.raw, 28, 4) as u8
    }

    pub fn set_pwm_lim(&mut self, v: u8) -> &mut Self {
        self.raw = set_bit_field(self.raw, 28, 4, v as u32);
        self
    }
}

/// PWM_SCALE – PWM scale value
/// (R) Addr: 0x71
#[repr(transparent)]
#[derive(Clone, Copy, Debug)]
pub struct PWM_SCALE {
    raw: u32
}

impl Register for PWM_SCALE {
    fn addr() -> u8 { 0x71 }
    fn from_raw(value: u32) -> Self { Self { raw: value } }
    fn to_raw(&self) -> u32 { self.raw }
}

impl PWM_SCALE {
    /// PWM_SCALE_SUM:
    /// Actual PWM duty cycle. (0...255)
    pub fn pwm_scale_sum(&self) -> u8 {
        get_bit_field(self.raw, 0, 8) as u8
    }

    /// PWM_SCALE_AUTO:
    /// 9 Bit signed offset added to the
    /// calculated PWM duty cycle.
    pub fn pwm_scale_auto(&self) -> u16 {
        get_bit_field(self.raw, 16, 9) as u16
    }
}

/// PWM_AUTO – Automatically determined PWM scale values
/// (R) Addr: 0x72
#[repr(transparent)]
#[derive(Clone, Copy, Debug)]
pub struct PWM_AUTO {
    raw: u32
}

impl Register for PWM_AUTO {
    fn addr() -> u8 { 0x72 }
    fn from_raw(value: u32) -> Self { Self { raw: value } }
    fn to_raw(&self) -> u32 { self.raw }
}

impl PWM_AUTO {
    /// PWM_OFS_AUTO:
    /// Automatically determined offset value (0...255)
    pub fn pwm_ofs_auto(&self) -> u8 {
        get_bit_field(self.raw, 0, 8) as u8
    }

    /// PWM_GRAD_AUTO:
    /// Automatically determined gradient value (0...255)
    pub fn pwm_grad_auto(&self) -> u8 {
        get_bit_field(self.raw, 16, 8) as u8
    }
}