rust_binary(
    name = "spi_flash",
    bin = "spi_flash"
)

rust_binary(
    name = "gpio",
    bin = "gpio"
)

rust_binary(
    name = "serial_shell",
    bin = "serial_shell"
)

rust_binary(
    name = "i2c",
    bin = "i2c"
)

rust_binary(
    name = "adxl_read",
    bin = "adxl_read"
)
