[package]
name = "fan_controller"
version = "0.0.1"
authors = ["Dennis Shtatnov <densht@gmail.com>"]
edition = '2018'

[dependencies]
executor = { path = "../executor", default-features = false }

[workspace]