[package]
name = "rpc_util"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
automata = { path = "../automata" }
protobuf = { path = "../protobuf" }
macros = { path = "../macros" }
rpc = { path = "../rpc" }
http = { path = "../http" }
grpc_proto = { path = "../../third_party/grpc_proto" }

[features]
default = ["std"]
std = ["alloc"]
alloc = []