[package]
name = "kicad"
version = "0.1.0"
edition = "2018"

[lib]
doctest = false

[dependencies]
macros = { path = "../../macros" }
math = { path = "../../math" }
common = { path = "../../common" }
parsing = { path = "../../parsing" }
reflection = { path = "../../reflection" }
executor = { path = "../../executor" }
file = { path = "../../file" }
xml = { path = "../../format/xml" }
protobuf = { path = "../../protobuf" }
kicad_proto = { path = "./proto" } 
base_error = { path = "../../base/error" }
base_radix = { path = "../../base/radix" }
protobuf_core = { path = "../../protobuf/core" }

[features]
default = ["std", "alloc"]
alloc = []
std = []