[package]
name = "protobuf_compiler"
version = "0.1.0"
authors = ["Dennis Shtatnov <densht@gmail.com>"]
edition = "2018"

[dependencies]
common = { path = "../common" }
parsing = { path = "../parsing" }
protobuf_core = { path = "../protobuf_core" }
protobuf_descriptor = { path = "../../third_party/protobuf_descriptor" }