[package]
name = "common"
version = "0.1.0"
authors = ["Dennis Shtatnov <densht@gmail.com>"]
edition = "2018"

[dependencies]
fs2 = "0.4.3"
libc = "0.2"
hex = "0.3.2"
base64 = "0.11.0"
async-trait = "0.1.30"
failure = "0.1.6"
futures = "0.3.4"
bytes = { git = "https://github.com/tokio-rs/bytes" }
lazy_static = "1.4.0"

[dependencies.async-std]
version = "1.5.0"
#git = "https://github.com/async-rs/async-std"
#features = ["unstable"]