[package]
name = "common"
version = "0.1.0"
authors = ["Dennis Shtatnov <densht@gmail.com>"]
edition = "2018"

[dependencies]
fs2 = "0.4.3"
libc = "0.2"
error-chain = "0.12.0"
hex = "0.3.2"
base64 = "0.11.0"
async-trait = "0.1.13"
async-std = "0.99.4"