[package]
name = "dymo"
version = "0.1.0"
authors = ["Dennis Shtatnov <densht@gmail.com>"]
edition = "2018"

[dependencies]
common = { path = "../common" }
usb = { path = "../usb" }
graphics = { path = "../graphics" }
image = { path = "../image" }