syntax = "proto3";

package cnc;

message PCBProcessorConfig {

    IsolationRoutingProcessorConfig isolation = 1;

    DrillProcessorConfig drill = 2;

    CutOutProcessorConfig cutout = 3;

    IsolationRoutingProcessorConfig mask_removal = 4;

    IsolationRoutingProcessorConfig paste_stencil = 5;

    // Changes all drill holes in the PCB to have this size.
    float forced_hole_diameter = 6;

    AlignmentHolesConfig alignment_holes = 7;

    DoubleSidedConfig double_sided = 8;

    ArcMotionBuilderConfig arc_builder = 9;

    LaserStencilProcessorConfig laser_stencil = 10;

    float min_feature_size = 11;
}

message AlignmentHolesConfig {
    // Size of the alignment hole to drill.
    float hole_size = 1;

    float long_edge_offset = 2;

    float short_edge_offset = 3;

    float short_edge_asymetric_offset = 4;
}

message DoubleSidedConfig {
    float front_through_cut_depth = 1;

    float back_through_cut_depth = 2;
    
    float front_partial_cut_depth = 3;
    
    float back_partial_cut_depth = 4;

    // float front_through_drill_depth = 5;
}

message ArcMotionBuilderConfig {
    // Minimum number of points in a plane needed to form an arc.
    // This is also the number of points over which the arc approximation will be computed.
    uint32 min_points = 1;

    // Maximum distance from any of the original gcode line segments to the formed arc curve.
    // (for each line segment, this would be the measured at the furthest point in the line segment from any point on the arc).
    //
    // This should be >= max_point_deviation
    float max_deviation = 2;

    // Maximum distance from any of the original gcode line endpoints to the formed arc curve.
    //
    // When the input points are interpolated from some original curve geometry, this should be > the max error
    // allowed during linearization in that just.
    float max_point_deviation = 3;

    // Maximum radius of the formed arc.
    float max_radius = 4;

    // 0-1 percentage change in the absolute value length of the new arc compared to the original set of line segments.
    //
    // While in theory max_deviation should be sufficient, the path length calculation is simpler and more robust.
    float max_path_length_deviation_percent = 5;

    // Maximum ratio between the 'longest_segment:shortest_segment' in the input line segments used to approximate
    // a curve.
    //
    // Set to >= 1
    float max_segment_variance = 6;
}

message SideAlignmentData {
    message PointMapping {
        repeated float point = 1;
        repeated float front_measurement = 2;
        repeated float back_measurement = 3;
    }    

    repeated PointMapping mappings = 1;
}


message IsolationRoutingProcessorConfig {
    uint32 tool_index = 1;
    
    // Diameter of the tool bit. For 'V' ('\_/') geometry bits, this is the diameter of the flat
    // bottom edge of the bit. 
    float tool_diameter = 2;

    float tool_v_angle = 3;

    // How thick the copper layer on the blank PCB is.
    // This is mainly used to verify that we are cutting deep enough to clear all of it.
    float min_cut_depth = 4;

    // Desired width of the empty space measured on the top of the PCB cut each by each line stroke of the engraving bit.
    //
    // If not specified, we assume it is the same as tool_diameter and we are 
    float cut_width = 5;

    // Desired cut depth. If not provided, this is derived from the cut_with for cut cutter tools.
    float cut_depth = 6;

    // Extra depth in Z distance we should plunge down (added to cut_depth). We assume that we are still staying at most at cut_depth but that some spring force is allowing us to compress the bit more.
    float cut_compression = 18;

    // Number of parallel isolation passes to take around the copper contours.
    //
    // If zero, we will make as many passes as necessary to clear all material up to the material edge.
    uint32 num_passes = 7;

    // From 0-1, the percentage of overlap between each pass.
    float overlap_percentage = 8;

    float spindle_speed = 9;

    // Safe Z above the material at which we can travel while within the X/Y bounds of the design.
    float travel_z = 10;

    float feedrate_xy = 11;

    float feedrate_z = 12;

    float rapid_feedrate = 13;

    // If true, cut inwards instead of cutting outwards.
    bool inverted = 14;

    // Globally safe Z height at which we can travel without hitting anything on the entire machine.
    float clearance_z = 15;

    // Number of times to run each pass.
    uint32 multiples = 16;

    float erosion = 17;
}

message DrillProcessorConfig {
    float rapid_feedrate = 1;

    float feedrate_z = 2;

    float spindle_speed = 3;

    float travel_z = 4;

    float drill_z = 5;

    // NOTE: This will be used for all holes.
    uint32 tool_index = 6;

    float tool_diameter = 7;

    float clearance_z = 8;

    repeated DrillTool tools = 9;

    reserved 6, 7;
}

message DrillTool {
    // NOTE: This will be used for all holes.
    uint32 tool_index = 1;

    float tool_diameter = 2;
}

message CutOutProcessorConfig {

    uint32 tool_index = 1;

    float tool_diameter = 2;

    // Amount of space (in mm) to leave around the edge cuts layer.
    float margin = 3;

    float feedrate_xy = 4;

    float feedrate_z = 5;

    float travel_z = 6;

    float cut_depth_z = 7;

    float depth_per_pass_z = 8;

    float spindle_speed = 9;

    float clearance_z = 10;

    float rapid_feedrate = 11;
}

message LaserStencilProcessorConfig {
    float laser_diameter = 1;
}
