[package]
name = "macros"
version = "0.1.0"
authors = ["Dennis Shtatnov <densht@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.23", features = ["extra-traits", "full"] }
quote = "1.0.6"
proc-macro2 = "1.0.13"