[package]
name = "parsing_compiler"
version = "0.1.0"
edition = "2018"

[dependencies]
common = { path = "../../common" }
protobuf = { path = "../../protobuf" }
parsing_compiler_proto = { path = "./proto" }
macros = { path = "../../macros" }
file = { path = "../../file" }
parsing = { path = "../../parsing" }
skylark = { path = "../../builder/skylark" }

[features]
default = ["std"]
std = ["alloc"]
alloc = []