[package]
name = "parsing_compiler"
version = "0.1.0"
edition = "2018"

[dependencies]
common = { path = "../../common" }
protobuf = { path = "../../protobuf" }
macros = { path = "../../macros" }
file = { path = "../../file" }
parsing = { path = "../../parsing" }
skylark = { path = "../../skylark" }

[build-dependencies]
protobuf_compiler = { path = "../../protobuf/compiler" }

[features]
default = ["std"]
std = ["alloc"]
alloc = []