[package]
name = "haystack"
version = "0.1.0"
authors = ["Dennis Shtatnov <densht@gmail.com>"]


[lib]
name = "haystack"
path = "lib.rs"

[[bin]]
name = "haystore"
path = "bin/haystore.rs"

[[bin]]
name = "haycache"
path = "bin/haycache.rs"

[[bin]]
name = "hayclient"
path = "bin/hayclient.rs"

[dependencies]
byteorder = "1.2.7"
rand = "0.6.1"
crc32c = "0.4.0"
arrayref = "0.3.5"
hyper = "0.12.19"
futures = "0.1.25"
futures-await = "0.1.1"
bytes = "0.4.11"
base64 = "0.10.0"
fs2 = "0.4.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
diesel = { version = "= 1.3.3", features = ["postgres", "chrono"] }
dotenv = "0.9.0"
mime-sniffer = "^0.1"
ipnetwork = "0.13.1"
chrono = "0.4.6"
bitwise = "0.1.1"
error-chain = "0.12.0"
reqwest = "0.9.5"
clap = "2.32.0"
rustc-serialize = "0.3"

