[package]
name = "media_camera"
version = "0.0.0"
edition = "2018"

[dependencies]
base_error = { path = "../../base/error" }
common = { path = "../../common" }
compression = { path = "../../compression" }
math = { path = "../../math" }
macros = { path = "../../macros" }
parsing = { path = "../../parsing" }
executor = { path = "../../executor" }
executor_multitask = { path = "../../executor/multitask" }
executor_graph = { path = "../../executor/graph" }
file = { path = "../../file" }
crypto = { path = "../../crypto" }
web = { path = "../../web" }
rpc = { path = "../../rpc" }
http = { path = "../../http" }
image = { path = "../../image" }
http_util = { path = "../../http/util" }
rpc_util = { path = "../../rpc/util" }
json = { path = "../../format/json" }
video = { path = "../video" }
v4l2 = { path = "../../../third_party/v4l2" }
usb = { path = "../../usb" }
protobuf = { path = "../../protobuf" }
libcamera = { path = "../../../third_party/libcamera", optional = true }
media_camera_proto = { path = "./proto" }

[features]
libcamera = ["dep:libcamera"]