[package]
name = "ptouch"
version = "0.1.0"
edition = "2018"

[dependencies]
common = { path = "../common" }
usb = { path = "../usb" }
graphics = { path = "../graphics" }
image = { path = "../image" }