[package]
name = "parsing"
version = "0.1.0"
authors = ["Dennis Shtatnov <densht@gmail.com>"]
edition = "2018"

[dependencies]
common = { path = "../common" }
bytes = { git = "https://github.com/tokio-rs/bytes" }