[package]
name = "rpi"
version = "0.1.0"
edition = "2018"

[dependencies]
common = { path = "../common" }
sys = { path = "../sys" }
file = { path = "../file" }
executor = { path = "../executor" }
parsing = { path = "../parsing" }
macros = { path = "../macros" }

[build-dependencies]
parsing_compiler = { path = "../parsing_compiler" }