[package]
name = "ptouch"
version = "0.1.0"
edition = "2018"

[dependencies]
base_error = { path = "../../../base/error" }
base_util = { path = "../../../base/util" }
usb = { path = "../../../usb" }
image = { path = "../../../image" }
executor = { path = "../../../executor" }
macros = { path = "../../../macros" }