[package]
name = "protobuf"
version = "0.1.0"
authors = ["Dennis Shtatnov <densht@gmail.com>"]
edition = "2018"

[dependencies]
common = { path = "../common", default-features = false }
parsing = { path = "../parsing", optional = true }
protobuf_core = { path = "../protobuf_core", default-features = false }
protobuf_descriptor = { path = "../../third_party/protobuf_descriptor", optional = true }
google = { path = "../../third_party/google", optional = true }
macros = { path = "../macros" }
json = { path = "../json", optional = true }
protobuf_compiler = { path = "../protobuf_compiler", optional = true }
file = { path = "../file", optional = true }

[build-dependencies]
protobuf_compiler = { path = "../protobuf_compiler" }

[features]
default = ["std"]
alloc = ["common/alloc", "protobuf_core/alloc"]
std = ["alloc", "common/std", "parsing", "protobuf_core/std", "protobuf_descriptor", "json", "protobuf_compiler", "google", "file"]