[package]
name = "protobuf"
version = "0.1.0"
edition = "2018"

[dependencies]
common = { path = "../common", default-features = false }
parsing = { path = "../parsing", optional = true }
protobuf_core = { path = "./core", default-features = false }
protobuf_descriptor = { path = "../../third_party/protobuf_descriptor", optional = true }
protobuf_builtins = { path = "../../third_party/protobuf_builtins", optional = true }
macros = { path = "../macros" }
json = { path = "../format/json", optional = true }
protobuf_compiler = { path = "./compiler", optional = true }
protobuf_compiler_proto = { path = "./compiler/proto", default-features = false }
protobuf_dynamic = { path = "./dynamic", optional = true }
file = { path = "../file", optional = true }
executor = { path = "../executor", optional = true }

[build-dependencies]
protobuf_compiler = { path = "./compiler" }
file = { path = "../file", optional = true }

[features]
default = ["std"]
alloc = ["common/alloc", "protobuf_core/alloc", "protobuf_compiler_proto/std"]
std = ["alloc", "common/std", "parsing", "protobuf_core/std", "protobuf_descriptor", "json", "protobuf_compiler", "protobuf_builtins", "file", "executor", "protobuf_dynamic", "protobuf_compiler_proto/std"]