[package]
name = "protobuf"
version = "0.1.0"
authors = ["Dennis Shtatnov <densht@gmail.com>"]
edition = "2018"

[dependencies]
common = { path = "../common" }
parsing = { path = "../parsing" }
base64 = "0.11.0"
protobuf_compiler = { path = "../protobuf_compiler" }
protobuf_core = { path = "../protobuf_core" }
protobuf_descriptor = { path = "../../third_party/protobuf_descriptor" }
macros = { path = "../macros" }
json = { path = "../json" }

[build-dependencies]
protobuf_compiler = { path = "../protobuf_compiler" }