[package]
name = "http"
version = "0.1.0"
authors = ["Dennis Shtatnov <densht@gmail.com>"]
edition = "2018"

[dependencies]
common = { path = "../common" }
parsing = { path = "../parsing" }
compression = { path = "../compression" }
async-std = "1.9.0"
arrayref = "0.3.5"