[package]
name = "usb"
version = "0.1.0"
authors = ["Dennis Shtatnov <densht@gmail.com>"]
edition = "2018"

[dependencies]
common = { path = "../common" }
libc = "0.2.97"
nix = "0.21.0"
arrayref = "0.3.5"