[package]
name = "usb"
version = "0.1.0"
edition = "2018"

[dependencies]
macros = { path = "../macros" }
automata = { path = "../automata", optional = true }
regexp_macros = { path = "../automata/regexp_macros" }
common = { path = "../common", default-features = false }
nix = { version = "0.21.0", optional = true }
failure = { version = "0.1.8", optional = true }
sys = { path = "../sys", optional = true }
executor = { path = "../executor", optional = true }
file = { path = "../file", optional = true }

[features]
default = ["std"]
std = ["alloc", "nix", "common/std", "automata", "sys", "executor", "file"]
alloc = ["common/alloc", "failure"]