[package]
name = "usb"
version = "0.1.0"
authors = ["Dennis Shtatnov <densht@gmail.com>"]
edition = "2018"

[dependencies]
macros = { path = "../macros" }
automata = { path = "../automata", optional = true }
regexp_macros = { path = "../regexp_macros" }
common = { path = "../common", default-features = false }
libc = { version = "0.2.97", optional = true }
nix = { version = "0.21.0", optional = true }
failure = { version = "0.1.8", optional = true }
sys = { path = "../sys", optional = true }

[features]
default = ["std"]
std = ["alloc", "nix", "libc", "common/std", "automata", "sys"]
alloc = ["common/alloc", "failure"]