[package]
name = "google_discovery"
version = "0.0.0"
edition = "2018"

[dependencies]
base_radix = { path = "../../../base/radix" }
common = { path = "../../../common" }
http = { path = "../../../http" }
json = { path = "../../../format/json" }
net = { path = "../../../net" }
parsing = { path = "../../../parsing" }
macros = { path = "../../../macros" }
automata = { path = "../../../automata" }
regexp_macros = { path = "../../../automata/regexp_macros" }
reflection = { path = "../../../reflection" }
executor = { path = "../../../executor" }
file = { path = "../../../file" }
