[package]
name = "rpc"
version = "0.1.0"
edition = "2018"

[dependencies]
common = { path = "../common" }
automata = { path = "../automata" }
regexp_macros = { path = "../automata/regexp_macros" }
parsing = { path = "../parsing" }
compression = { path = "../compression" }
http = { path = "../http" }
protobuf = { path = "../protobuf" }
macros = { path = "../macros" }
failure = "0.1.8"
protobuf_builtins = { path = "../../third_party/protobuf_builtins" }
googleapis_proto = { path = "../../third_party/googleapis" }
protobuf_json = { path = "../protobuf/json" }
executor = { path = "../executor" }
net = { path = "../net" }

[features]
default = ["std"]
std = ["alloc"]
alloc = []