[package]
name = "rpc"
version = "0.1.0"
authors = ["Dennis Shtatnov <densht@gmail.com>"]
edition = "2018"

[dependencies]
common = { path = "../common" }
automata = { path = "../automata" }
regexp_macros = { path = "../regexp_macros" }
parsing = { path = "../parsing" }
compression = { path = "../compression" }
http = { path = "../http" }
protobuf = { path = "../protobuf" }
macros = { path = "../macros" }
failure = "0.1.8"
google = { path = "../../third_party/google" }

[build-dependencies]
protobuf_compiler = { path = "../protobuf_compiler" }

[features]
default = ["std"]
std = ["alloc"]
alloc = []