[package]
name = "rpc"
version = "0.1.0"
authors = ["Dennis Shtatnov <densht@gmail.com>"]
edition = "2018"

[dependencies]
common = { path = "../common" }
parsing = { path = "../parsing" }
compression = { path = "../compression" }
http = { path = "../http" }
protobuf = { path = "../protobuf" }
bytes = { git = "https://github.com/tokio-rs/bytes" }
libc = "0.2.62"