[package]
name = "rpc_test"
version = "0.1.0"
authors = ["Dennis Shtatnov <densht@gmail.com>"]
edition = "2018"

[dependencies]
common = { path = "../common" }
rpc = { path = "../rpc" }
rpc_util = { path = "../rpc_util" }
protobuf = { path = "../protobuf" }
macros = { path = "../macros" }
http = { path = "../http" }
container = { path = "../container" }

[build-dependencies]
protobuf_compiler = { path = "../protobuf_compiler" }

[features]
default = ["std"]
std = ["alloc"]
alloc = []