[package]
name = "rpc_test"
version = "0.1.0"
edition = "2018"

[dependencies]
common = { path = "../common" }
rpc = { path = "../rpc" }
rpc_util = { path = "../rpc_util" }
protobuf = { path = "../protobuf" }
macros = { path = "../macros" }
http = { path = "../http" }
cluster_client = { path = "../container/client" }
file = { path = "../file" }
executor = { path = "../executor" }
executor_multitask = { path = "../executor/multitask" }

[build-dependencies]
protobuf_compiler = { path = "../protobuf/compiler" }

[features]
default = ["std"]
std = ["alloc"]
alloc = []