[package]
name = "emulator"
version = "0.1.0"
authors = ["Dennis Shtatnov <densht@gmail.com>"]
edition = "2018"

[dependencies]
common = { path = "../common" }
cpal = { git = "https://github.com/RustAudio/cpal" }
graphics = { path = "../graphics" }