[package]
name = "peripherals_raw"
version = "0.0.0"
edition = "2018"

[dependencies]
common = { path = "../../common", default-features = false }

[features]
default = ["std", "alloc"]
alloc = ["common/alloc"]
std = ["common/std"]