rust_binary(
    name = "entry_command"
)

local_binary(
    name = "entry_command_bin",
    deps = [
        ":entry_command"
    ]
)

rust_binary(
    name = "builder"
)

local_binary(
    name = "builder_bin",
    deps = [
        ":builder"
    ]
)