[package]
name = "builder"
version = "0.1.0"
edition = "2018"

[dependencies]
base_args = { path = "../base/args" }
common = { path = "../common" }
macros = { path = "../macros" }
protobuf = { path = "../protobuf" }
compression = { path = "../compression" }
crypto = { path = "../crypto" }
skylark = { path = "./skylark" }
protobuf_builtins = { path = "../../third_party/protobuf_builtins" }
file = { path = "../file" }
executor = { path = "../executor" }
base_radix = { path = "../base/radix" }
builder_proto = { path = "./proto" }

[target.'cfg(target_os = "linux")'.dependencies]
sys = { path = "../sys" }

[features]
default = ["std"]
std = ["alloc"]
alloc = []