[package]
name = "builder"
version = "0.1.0"
authors = ["Dennis Shtatnov <densht@gmail.com>"]
edition = "2018"

[dependencies]
common = { path = "../common" }
macros = { path = "../macros" }
protobuf = { path = "../protobuf" }
compression = { path = "../compression" }

[build-dependencies]
protobuf_compiler = { path = "../protobuf_compiler" }