[package]
name = "rp2040_programmer"
version = "0.1.0"
edition = "2018"

[dependencies]
common = { path = "../common" }
usb = { path = "../usb" }
elf = { path = "../elf" }
crypto = { path = "../crypto" }
parsing = { path = "../parsing" }
macros = { path = "../macros" }
executor = { path = "../executor" }
file = { path = "../file" }