[package]
name = "asn"
version = "0.1.0"
authors = ["Dennis Shtatnov <densht@gmail.com>"]
edition = "2018"

[dependencies]
math = { path = "../math" }
common = { path = "../common" }
parsing = { path = "../parsing" }
asn_compiler = { path = "../asn_compiler" }
