[package]
name = "datastore"
version = "0.1.0"
authors = ["Dennis Shtatnov <densht@gmail.com>"]
edition = "2018"

[dependencies]
common = { path = "../common" }
http = { path = "../http" }
rpc = { path = "../rpc" }
parsing = { path = "../parsing" }
sstable = { path = "../sstable" }
raft = { path = "../raft" }
protobuf = { path = "../protobuf" }
macros = { path = "../macros" }

[build-dependencies]
protobuf_compiler = { path = "../protobuf_compiler" }
