[package]
name = "peripheral"
version = "0.1.0"
edition = "2018"

[dependencies]
common = { path = "../common" }
parsing = { path = "../parsing" }
crypto = { path = "../crypto" }
rpi = { path = "../rpi" }
nix = "0.21.0"
libc = "0.2.97"
lazy_static = "1.4.0"