[package]
name = "sstable"
version = "0.1.0"
edition = "2018"

[dependencies]
common = { path = "../common" }
compression = { path = "../compression" }
crypto = { path = "../crypto" }
math = { path = "../math" }
macros = { path = "../macros" }
protobuf = { path = "../protobuf" }
protobuf_compiler_proto = { path = "../protobuf/compiler/proto" }
parsing = { path = "../parsing" }
file = { path = "../file" }
executor = { path = "../executor" }
executor_multitask = { path = "../executor/multitask" }
base_radix = { path = "../base/radix" }
sstable_proto = { path = "./proto" }

[features]
default = ["std"]
std = ["alloc"]
alloc = []