[package]
name = "file"
version = "0.1.0"
edition = "2024"

[dependencies]
automata = { path = "../automata" }
base_util = { path = "../base/util" }
common = { path = "../common" }
executor = { path = "../executor" }
macros = { path = "../macros" }
failure = "0.1.8"

[target.'cfg(target_os = "linux")'.dependencies]
sys = { path = "../sys" }