[package]
name = "gerber"
version = "0.1.0"
edition = "2018"

[lib]
doctest = false

[dependencies]
macros = { path = "../../macros" }
math = { path = "../../math" }
common = { path = "../../common" }
parsing = { path = "../../parsing" }
executor = { path = "../../executor" }
file = { path = "../../file" }
graphics = { path = "../../graphics" }
image = { path = "../../image" }
base_error = { path = "../../base/error" }
base_radix = { path = "../../base/radix" }
regexp_macros = { path = "../../automata/regexp_macros" }
automata = { path = "../../automata" }
reflection = { path = "../../reflection" }
glfw = "0.51.0"


[features]
default = ["std", "alloc"]
alloc = []
std = []