[package]
name = "cnc_tools"
version = "0.1.0"
edition = "2018"

[dependencies]
macros = { path = "../../macros" }
base_args = { path = "../../base/args" }
base_algorithms = { path = "../../base/algorithms" }
base_error = { path = "../../base/error" }
common = { path = "../../common" }
executor = { path = "../../executor" }
file = { path = "../../file" }
gcode = { path = "../gcode" }
rpc = { path = "../../rpc" }
usb = { path = "../../usb" }
math = { path = "../../math" }
media_camera = { path = "../../media/camera" }
math_compute = { path = "../../math/compute" }
math_proto_util = { path = "../../math/proto/util" }
math_proto = { path = "../../math/proto" }
crypto = { path = "../../crypto" }
protobuf = { path = "../../protobuf" }
executor_multitask = { path = "../../executor/multitask" }
peripherals_proto = { path = "../../peripherals/proto" }
cnc = { path = "../" }
sstable = { path = "../../sstable" }
cnc_controller = { path = "../controller" }
cnc_controller_proto = { path = "../controller/proto" }
cluster_client = { path = "../../cluster/client" }
cluster_proto = { path = "../../cluster/proto" }
peripherals_service = { path = "../../peripherals/service" }
