use std::collections::BTreeMap;
use std::io::Write;
use std::process::Command;

use common::errors::*;
use common::line_builder::LineBuilder;
use file::{project_path, LocalPath, LocalPathBuf};

use crate::compiler::{Compiler, CompilerOptions};
use crate::syntax::parse_proto;

pub fn project_default_options() -> CompilerOptions {
    let mut options = CompilerOptions::default();

    // TODO: Infer these from build dependencies.
    options
        .paths
        .push(project_path!("third_party/protobuf_builtins/proto"));
    options
        .paths
        .push(project_path!("third_party/googleapis/repo"));

    // TODO: This is a dangerous default() as we can't use it outside of a real
    // project.
    options.paths.push(file::project_dir());

    options
}

// TODO: Most of this code is identical across the different implements and
// could probably be refactored out!!
pub fn build() -> Result<()> {
    build_with_options(project_default_options())
}

pub fn build_with_options(options: CompilerOptions) -> Result<()> {
    // NOTE: This must be the root path of the package (containing the Cargo.toml
    // and build.rs).
    let input_dir = file::current_dir()?;

    let output_dir = LocalPathBuf::from(std::env::var("OUT_DIR")?);

    // TODO: How do we indicate that the directory could change (adding new files).

    // TODO: Propagate out the Results from inside the callback.

    build_custom(&input_dir, &output_dir, options)
}

#[derive(Default)]
struct PackageTree {
    files: Vec<LocalPathBuf>,
    child_packages: BTreeMap<String, PackageTree>,
}

impl PackageTree {
    fn insert(&mut self, package: &str, file: LocalPathBuf) {
        let mut package_path: Vec<&str> = package.split('.').collect::<Vec<_>>();
        if package.is_empty() {
            package_path.clear();
        }

        self.insert_with_path(&package_path[..], file)
    }

    fn insert_with_path(&mut self, package_path: &[&str], file: LocalPathBuf) {
        if package_path.is_empty() {
            self.files.push(file);
            return;
        }

        let inner = self
            .child_packages
            .entry(package_path[0].to_string())
            .or_default();
        inner.insert_with_path(&package_path[1..], file)
    }

    fn to_module(&self, options: &CompilerOptions, lines: &mut LineBuilder) {
        // lines.add("#![allow(dead_code, non_snake_case, unused_imports,
        // unused_variables)]");

        for (key, value) in self.child_packages.iter() {
            lines.add(format!("pub mod {} {{", key));
            Self::add_imports(options, lines);
            value.to_module(options, lines);
            lines.add("}");
        }

        for file in &self.files {
            lines.add(format!(
                r#"include!(concat!(env!("OUT_DIR"), "/{}"));"#,
                file.as_str()
            ));
        }
    }

    fn add_imports(options: &CompilerOptions, lines: &mut LineBuilder) {
        lines.add("// AUTOGENERATED BY PROTOBUF COMPILER\n");
        lines.add("#[cfg(feature = \"std\")] use std::sync::Arc;");
        lines.add("#[cfg(feature = \"alloc\")] use alloc::vec::Vec;");
        lines.add("#[cfg(feature = \"alloc\")] use alloc::string::String;\n");
        lines.add("#[cfg(feature = \"alloc\")] use alloc::boxed::Box;\n");
        lines.add("use common::errors::*;");
        lines.add("use common::list::Appendable;");
        lines.add("use common::collections::FixedString;");
        lines.add("use common::fixed::vec::FixedVec;");
        lines.add("use common::const_default::ConstDefault;");
        lines.add(format!("use {}::*;\n", options.runtime_package));
        lines.add(format!("use {}::codecs::*;\n", options.runtime_package));
        lines.add(format!("use {}::wire::*;\n", options.runtime_package));
        // lines.add(format!("use {}::service::*;\n", c.options.runtime_package));
        lines.add(format!(
            "#[cfg(feature = \"alloc\")] use {}::reflection::*;\n",
            options.runtime_package
        ));
    }
}

pub fn build_custom(
    input_dir: &LocalPath,
    output_dir: &LocalPath,
    options: CompilerOptions,
) -> Result<()> {
    let mut input_paths: Vec<LocalPathBuf> = vec![];

    file::recursively_list_dir(&input_dir, &mut |path: &LocalPath| {
        if path.extension().unwrap_or_default() != "proto" {
            return;
        }

        if let Some(allowlisted_paths) = &options.allowlisted_paths {
            let mut allowed = false;
            for p in allowlisted_paths {
                if path.starts_with(p) {
                    allowed = true;
                    break;
                }
            }

            if !allowed {
                return;
            }
        }

        input_paths.push(path.to_owned());
    })?;

    let mut tree = PackageTree::default();

    // TODO: Parallelize this?
    for input_path in input_paths {
        let mut relative_path = input_path.strip_prefix(&input_dir).unwrap().to_owned();
        println!("cargo:rerun-if-changed={}", relative_path.as_str());

        let input_src = std::fs::read_to_string(&input_path)?;

        let desc = match parse_proto(&input_src) {
            Ok(d) => d,
            Err(e) => {
                return Err(format_err!("Failed to parse {:?}: {:?}", relative_path, e));
            }
        };

        relative_path.set_extension("rs");
        let mut output_path: LocalPathBuf = output_dir.join(&relative_path);

        std::fs::create_dir_all(output_path.parent().unwrap())?;

        let output = Compiler::compile(&desc, &input_path, input_dir, &options)?;
        std::fs::write(&output_path, output)?;

        tree.insert(&desc.package, relative_path);

        if options.should_format {
            // TODO: This doesn't work with 'cross'
            let res = Command::new("rustfmt").arg(output_path.as_str()).output()?;
            if !res.status.success() {
                std::io::stdout().write_all(&res.stdout).unwrap();
                std::io::stderr().write_all(&res.stderr).unwrap();
                return Err(err_msg("rustfmt failed"));
            }
        }
    }

    let mut lines = LineBuilder::new();

    PackageTree::add_imports(&options, &mut lines);
    tree.to_module(&options, &mut lines);

    let mod_path = output_dir.join("proto_lib.rs");
    std::fs::write(&mod_path, lines.to_string())?;

    Ok(())
}
