[package]
name = "protobuf_bench"
version = "0.1.0"
edition = "2018"

[dependencies]
common = { path = "../../common" }
protobuf = { path = ".." }

[build-dependencies]
protobuf_compiler = { path = "../compiler" }

[features]
default = ["std"]
std = ["alloc"]
alloc = []