[package]
name = "nordic_proto"
version = "0.0.0"
edition = "2018"

[lib]
path = "lib.rs"

[dependencies]
common = { path = "../../common", default-features = false }
protobuf = { path = "../../protobuf", default-features = false }
macros = { path = "../../macros" }
protobuf_compiler_proto = { path = "../../protobuf/compiler/proto", optional = true }

[build-dependencies]
protobuf_compiler = { path = "../../protobuf/compiler" }

[features]
default = ["std"]
std = ["alloc", "common/std", "protobuf/std", "protobuf_compiler_proto"]
alloc = ["common/alloc", "protobuf/alloc"]
