[package]
name = "parsing_test"
version = "0.1.0"
edition = "2018"

[dependencies]
common = { path = "../common" }
parsing = { path = "../parsing" }

[build-dependencies]
parsing_compiler = { path = "../parsing/compiler" }