[package]
name = "markdown"
version = "0.0.0"
edition = "2018"

[dependencies]
common = { path = "../common" }
parsing = { path = "../parsing" }
automata = { path = "../automata" }
regexp_macros = { path = "../automata/regexp_macros" }