[package]
name = "cluster_meta"
version = "0.1.0"
edition = "2018"

[dependencies]
base_error = { path = "../../base/error" }
common = { path = "../../common" }
base_radix = { path = "../../base/radix" }
db_kv = { path = "../../db/kv" }
db_table = { path = "../../db/table" }
crypto = { path = "../../crypto" }
protobuf = { path = "../../protobuf" }
http = { path = "../../http" }
macros = { path = "../../macros" }
db_txn = { path = "../../db/txn" }
db_txn_proto = { path = "../../db/txn/proto" }
compression = { path = "../../compression" }
cluster_client = { path = "../../cluster/client" }
cluster_proto = { path = "../../cluster/proto" }
rpc = { path = "../../rpc" }
rpc_util = { path = "../../rpc/util" }
net = { path = "../../net" }
raft = { path = "../../raft" }
protobuf_builtins = { path = "../../../third_party/protobuf_builtins" }
executor = { path = "../../executor" }
executor_multitask = { path = "../../executor/multitask" }
file = { path = "../../file" }
sstable = { path = "../../sstable" }

[features]
default = ["std"]
std = ["alloc"]
alloc = []