syntax = "proto3";

package cnc;

import "pkg/peripherals/proto/service.proto";
import "pkg/cnc/motion/proto/config.proto";


message ControllerConfig {
    string name = 1;

    message DeviceEntry {
        string name = 1;

        peripherals.BoardConfig peripheral_config = 2;

        BedClientConfig bed_client = 3;

        peripherals.TMC2209Config tmc2209 = 4;
    }

    repeated DeviceEntry devices = 2;

    MotionControllerConfig motion_controller = 3;

    repeated HeaterControllerConfig heater_controllers = 5;

    EndstopControllerConfig endstop_controller = 6;

    // For now this should always have 4 numbers.
    repeated float bed_fem_weights = 4;

    // Names of all endstops that should be normally monitored
    // (when motors are energized but not homing).
    repeated string default_endstops = 7;
}

message HeaterControllerConfig {

    PeripheralReference thermistor = 1;

    PeripheralReference heater = 2;


}

message PeripheralReference {
    string device_name = 1;
    string peripheral_name = 2;
}

message BedClientConfig {
    float bed_temp_resistor = 1;
    float sheet_temp_resistor = 2;
    float aux_temp_resistor = 3;

    float calibration_a = 4;
    float calibration_b = 5;
    float chip_temp_calibration = 6;
}


message MotionControllerConfig {
    message Motor {
        string device_name = 1;
        bool inverted = 2;
        float steps_per_mm = 3;
    }

    repeated Motor motors = 1;

    repeated AxisGeometry geometry = 2;

    repeated Axis axes = 3;

    LinearMotionPlannerConfig planner = 6;
}

message Axis {
    // (also used as the default acceleration)
    float max_acceleration = 1;

    // (also used as the default speed)
    float max_speed = 2;

    string name = 3;

    // Determines how the feed rate is interprated.
    // - The axe with the lowest priority that is moving determined the overall coordination_priority.
    // - Only axes at that coordination_priority follow
    //   the feedrate. Other axes are driven at whatever
    //   speed is needed to coordinate them with the main
    //   axes.
    uint32 coordination_priority = 4;
}

message EndstopControllerConfig {
    repeated Endstop endstops = 1;
}

message Endstop {
    string name = 1;

    PeripheralReference peripheral = 2;

    // When this endstop is triggered, this list of motors will be immediately stopped.
    repeated string motors = 3;

    // If true, then when this endstop is hit, it means that the associated motors will
    // lose their step position when this endstop is hit.
    bool hard = 4;

    // If present, then this is a list of buffers
    // to use for scanning an analog endstop.
    repeated string analog_buffers = 5;
}

message AxisGeometry {
    message Direct {
        string motor_name = 1;
        uint32 motor_index = 2;

        uint32 axis_index = 3;
    }

    message CoreXY {
        uint32 x_axis_index = 1;

        uint32 y_axis_index = 2;
        
        string a_motor_name = 3;
        uint32 a_motor_index = 4;

        string b_motor_name = 5;
        uint32 b_motor_index = 6;
    }

    oneof geometry {
        Direct direct = 1;
        CoreXY core_xy = 2;
    }
}


