syntax = "proto3";

package cnc;

import "pkg/peripherals/proto/service.proto";
import "pkg/cnc/motion/proto/config.proto";


service Controller {
    rpc Execute (ExecuteRequest) returns (ExecuteResponse);
}

message ExecuteRequest {
    repeated Command commands = 1;
}

message ExecuteResponse {

}

message Command {
    MoveToCommand move_to = 1;
    HomeCommand home = 2;
    SetTemperatureCommand set_temp = 3;
    SetPosition set_position = 4;
    ConfigureCommand configure = 5;
    bool reset_alarm = 6;
}

message MoveToCommand {
    float x = 1;
    float y = 2;
    float z = 3;
    float e = 4;

    float feed_rate = 5;

    float max_acceleration = 6;
}

message HomeCommand {}

message SetTemperatureCommand {
    float target = 1;
}

message SetPosition {
    float x = 1;
    float y = 2;
    float z = 3;
    float e = 4;
}

message ConfigureCommand {
    float max_junction_deviation = 1;
}