syntax = "proto3";

package cnc;

import "pkg/peripherals/proto/service.proto";
import "pkg/cnc/motion/proto/config.proto";
import "pkg/cnc/controller/proto/log.proto";
import "pkg/cnc/controller/proto/matrix.proto";


service Controller {
    rpc GetState (GetStateRequest) returns (GetStateResponse);

    rpc Execute (ExecuteRequest) returns (ExecuteResponse);

    // Use this if you need to enqueue many requests with some total ordering between requests.
    // TODO: Think about whether or not we should decouple errors between stream items.
    rpc ExecuteStream (stream ExecuteRequest) returns (stream ExecuteResponse);

    rpc GetLastPosition (GetLastPositionRequest) returns (GetLastPositionResponse);

    rpc ReadLog (ReadLogRequest) returns (stream ReadLogResponse);
}

message GetStateRequest {

}

message GetStateResponse {
    VectorProto position = 1;

    float heater_temp = 2;

    float heater_target = 3;
}


message ExecuteRequest {
    repeated Command commands = 1;

    // Used in ExecuteStream to correlate responses with requests.
    uint64 request_id = 2;
}

message ExecuteResponse {

    VectorProto last_position = 1;

    VectorProto hit_position = 2;

    uint64 request_id = 3;
}

message Command {
    oneof command {
        MoveToCommand move_to = 1;
        HomeCommand home = 2;
        SetTemperatureCommand set_temp = 3;
        SetPosition set_position = 4;
        ConfigureCommand configure = 5;
        bool reset_alarm = 6;
        bool wait_until_idle = 7;
        SetFanSpeed set_fan_speed = 8;
        SetServoPosition set_servo_position = 9;
        SetLedStripColors set_led_strip = 10;
    }
}

message SetFanSpeed {
    float speed = 1;

    string name = 2;
}

message SetServoPosition {
    // Position in microseconds.
    float position = 1;
}

message SetLedStripColors {
    string name = 1;
    bytes data = 2;
}

message MoveToCommand {
    double x = 1;
    double y = 2;
    double z = 3;
    double e = 4;

    // Alternative way to specify the next position
    VectorProto position = 8;

    bool towards_endstop = 7;

    MoveOptionsProto options = 9;

    bool wait_for_completion = 10;

    reserved 5, 6;
}

message MoveOptionsProto {
    double feed_rate = 1;
    optional double acceleration = 2;
    bool force = 3;
}

message HomeCommand {
    bool skip_z = 1;
}

message SetTemperatureCommand {
    float target = 1;
}

message SetPosition {
    VectorProto position = 1;
}

message ConfigureCommand {
    double max_junction_deviation = 1;
}

message GetLastPositionRequest {

}

message GetLastPositionResponse {
    VectorProto position = 1;
}

message SkewData {
    message Point {
        uint32 fixed_group = 1;

        VectorProto machine_position = 2;

        uint32 image_index = 3;

        fixed64 time_micros = 4;

    }

    repeated Point points = 1;
}



message ReadLogRequest {
    
}

message ReadLogResponse {
    LogEntry entry = 1;

}
