syntax = "proto3";

package cluster;

import "pkg/cluster/proto/config.proto";

// Config parameters used to start up a single Node instance.
message NodeConfig {
    // Path to a directory into which we will store all container related data.
    string data_dir = 1;

    // Path to use for the node's cgroup v2 subtree. The node process and all container processes
    // will live somewhere in this tree.
    //
    // If empty, then we assume that the node already exists in a suitable cgroup that its
    // running uid can control.
    string cgroup_dir = 11;

    // Port used for the main node management service.
    int32 service_port = 2;

    // Base template used to construct worker containers.
    ContainerConfig container_template = 3;
    
    // Maximum amount of time in seconds after a container is terminated with a signal before we
    // forcefully kill it.
    uint32 graceful_shutdown_timeout_secs = 4;

    // Range of network ports which may be used by workers running on this node.
    // TODO: Have the node runtime validate that we only receive workers with ports in this range.
    //
    // NOTE: This is mainly for ports that are auto-assigned. node_ports don't need to be in this
    // range.
    PortRange allocatable_port_range = 6;

    // Name of the cluster zone this node is a part of.
    string zone = 7;

    // If non-empty, all containers are started using an 'init' process running the binary
    // specified in init_process_args[0].
    //
    // The full list of arguments passed to the init process will be
    // [init_process_args, "--", worker_args]. The expectation is that the init process will
    // run the worker binary based on the given arguments.
    repeated string init_process_args = 10;

    // Unique identifier for this node in the cluster.
    // The value of this MUST NOT change after the first startup.
    fixed64 id = 13;

    // If true, the node will use mTLS for all communications.
    bool secure = 14;

    // List of network interfaces on which we will enable hardware TX/RX timestamping.
    //
    // This is setup in the kernel early while the node still has CAP_NET_ADMIN.
    //
    // Note that there is currently no way to restrict which workers on a node use this
    // feature once it is enabled.
    repeated string hardware_timestamped_interfaces = 15;

    reserved 5, 12;
}

// Represents all port numbers in the range [start, end).
message PortRange {
    uint32 start = 1;
    uint32 end = 2;
}