syntax = "proto3";

package cluster;

import "pkg/cluster/proto/certificates.proto";


// Data stored on a node running a worker to keep track of important internal data for
// running the worker.
message WorkerRuntimeMetadata {
    string worker_name = 1;

    // Linux uid used to run the worker processes.
    // (unique between workers and persists across restarts)
    uint32 user_id = 2;

    // Linux gid used to run the worker processes.
    // (unique between workers and persists across restarts)
    uint32 group_id = 3;
}