[package]
name = "perf"
version = "0.1.0"
edition = "2018"

[dependencies]
common = { path = "../common" }
parsing = { path = "../parsing" }
sys = { path = "../sys" }

[features]
default = ["std"]
std = ["alloc"]
alloc = []