[package]
name = "perf"
version = "0.1.0"
edition = "2018"

[dependencies]
common = { path = "../common" }
parsing = { path = "../parsing" }
protobuf = { path = "../protobuf" }
sys = { path = "../sys" }
elf = { path = "../elf" }
executor = { path = "../executor" }
file = { path = "../file" }
google = { path = "../../third_party/google" }
base_radix = { path = "../base/radix" }

[features]
default = ["std"]
std = ["alloc"]
alloc = []