[package]
name = "mocap_tools"
version = "0.1.0"
edition = "2018"

[dependencies]
common = { path = "../../../common" }
builder = { path = "../../../builder" }
base_args = { path = "../../../base/args" }
file = { path = "../../../file" }
cluster_client = { path = "../../../cluster/client" }
cluster_proto = { path = "../../../cluster/proto" }
peripherals = { path = "../../../peripherals" }
peripherals_devices = { path = "../../../peripherals/devices" }
peripherals_service = { path = "../../../peripherals/service" }
executor = { path = "../../../executor" }
executor_multitask = { path = "../../../executor/multitask" }
parsing = { path = "../../../parsing" }
macros = { path = "../../../macros" }
image = { path = "../../../image" }
math = { path = "../../../math" }
math_proto_util = { path = "../../../math/proto/util" }
protobuf = { path = "../../../protobuf" }
perf = { path = "../../../perf" }
protobuf_json = { path = "../../../protobuf/json" }
rpc = { path = "../../../rpc" }
net = { path = "../../../net" }
ptp = { path = "../../../net/ptp" }
ptp_proto = { path = "../../../net/ptp/proto" }
http = { path = "../../../http" }
http_util = { path = "../../../http/util" }
web = { path = "../../../web" }
rpc_util = { path = "../../../rpc/util" }
protobuf_builtins = { path = "../../../../third_party/protobuf_builtins" }
mocap_proto = { path = "../proto" }
mocap_camera_core = { path = "../camera/core" }
mocap_manager = { path = "../manager" }
mocap_simulation = { path = "../simulation" }
vision = { path = "../../" }
sstable = { path = "../../../sstable" }
rpi = { path = "../../../rpi" }
rpi_imager = { path = "../../../rpi/imager" }
scpi = { path = "../../../peripherals/scpi" }
pio_rp1 = { path = "../../../rpi/pio_rp1" }