[package]
name = "peripherals_service"
version = "0.1.0"
edition = "2018"

[dependencies]
base_error = { path = "../../base/error" }
base_util = { path = "../../base/util" }
common = { path = "../../common" }
usb = { path = "../../usb" }
graphics = { path = "../../graphics" }
image = { path = "../../image" }
executor = { path = "../../executor" }
executor_multitask = { path = "../../executor/multitask" }
file = { path = "../../file" }
crypto = { path = "../../crypto" }
protobuf = { path = "../../protobuf" }
cluster_client = { path = "../../cluster/client" }
cluster_proto = { path = "../../cluster/proto" }
peripherals_proto = { path = "../proto" }
macros = { path = "../../macros" }
http = { path = "../../http" }
json = { path = "../../format/json" }
web = { path = "../../web" }
nordic_driver = { path = "../../nordic/driver" }
parsing = { path = "../../parsing" }
rpc = { path = "../../rpc" }
storage = { path = "../../storage" }
rpc_util = { path = "../../rpc/util" }
electronics = { path = "../electronics" }