name: "system.cert-authority"
replicas: 1
scheduling {
    distinct_nodes: true
    labels {
        label {
            key: "system"
            present: true
        }
    }
}
worker {
    persistent: true

    args: [
        "/volumes/bundle/built/pkg/cluster/ca/cluster_ca",
        "--port=service"
    ]

    ports {
        name: "service"
        type: TCP
    }

    volumes: [
        {
            name: "bundle"
            build_target: "//pkg/cluster/ca:bundle"
        }
    ]
}