name: "system.meta"
replicas: 1
scheduling {
    distinct_nodes: true
    labels {
        label {
            key: "system"
            present: true
        }
    }
}
worker {
    persistent: true

    args: [
        "/volumes/bundle/built/pkg/cluster/meta/cluster_meta",
        "--port=service",
        "--dir=/volumes/data"
    ]

    ports {
        name: "service"
        type: TCP
    }

    volumes: [
        {
            name: "bundle"
            build_target: "//pkg/cluster/meta:cluster_meta_bundle"
        },
        {
            name: "data"
            persistent: true
        }
    ]
}