[package]
name = "perf_util"
version = "0.1.0"
edition = "2018"

[dependencies]
common = { path = "../common" }
parsing = { path = "../parsing" }
protobuf = { path = "../protobuf" }
compression = { path = "../compression" }
sys = { path = "../sys" }
elf = { path = "../elf" }
perf = { path = "../perf" }
protobuf_builtins = { path = "../../third_party/protobuf_builtins" }
file = { path = "../file" }
executor = { path = "../executor" }

[features]
default = ["std"]
std = ["alloc"]
alloc = []