# TODO: Support pre-gziping the data.
filegroup(
    name = "web_data",
    srcs = [
        # TODO: The raw index.html is not needed for web serving (just for internal templating).
        "index.html",
        "style.css",
        "//node_modules/bootstrap/dist/css/bootstrap.min.css",
        "//third_party/noto_sans/font_normal.ttf",
        "//third_party/noto_sans/font_mono_normal.ttf",
        "//third_party/material_icons/material_symbols_outlined.woff2",
    ]
)

filegroup(
    name = "public_assets",
    srcs = [

    ]
)
