webpack(
    name = "app",
    entry = "lib/index.tsx"
)

# TODO: Support pre-gziping the data.
filegroup(
    name = "web_data",
    srcs = [
        "index.html",
        "style.css",
        "//node_modules/bootstrap/dist/css/bootstrap.min.css",
        "//third_party/noto_sans/font_normal.ttf",
        "//third_party/noto_sans/font_mono_normal.ttf",
        "//third_party/material_icons/material_symbols_outlined.woff2",
    ]
)