webpack {
    name: "app"
    entry: "lib/index.tsx"
}

# TODO: Support pre-gziping the data.
filegroup {
    name: "web_data",
    srcs: [
        "index.html",
        "//node_modules/bootstrap/dist/css/bootstrap.min.css",
        "//third_party/noto_sans/font_normal.ttf"
    ]
}