[package]
name = "web"
version = "0.1.0"
edition = "2018"

[dependencies]
common = { path = "../common" }
http = { path = "../http" }
rpc = { path = "../rpc" }
automata = { path = "../automata" }
parsing = { path = "../parsing" }
regexp_macros = { path = "../automata/regexp_macros" }
protobuf = { path = "../protobuf" }
protobuf_json = { path = "../protobuf/json" }
macros = { path = "../macros" }
rpc_test = { path = "../rpc_test" }
json = { path = "../format/json" }
file = { path = "../file" }
executor = { path = "../executor" }