[package]
name = "mocap_manager"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../../../common" }
base_args = { path = "../../../base/args" }
file = { path = "../../../file" }
net = { path = "../../../net" }
net_iface = { path = "../../../net/iface" }
cluster_client = { path = "../../../cluster/client" }
cluster_proto = { path = "../../../cluster/proto" }
executor = { path = "../../../executor" }
executor_multitask = { path = "../../../executor/multitask" }
parsing = { path = "../../../parsing" }
macros = { path = "../../../macros" }
image = { path = "../../../image" }
math = { path = "../../../math" }
math_proto_util = { path = "../../../math/proto/util" }
protobuf = { path = "../../../protobuf" }
protobuf_json = { path = "../../../protobuf/json" }
rpc = { path = "../../../rpc" }
ptp_core = { path = "../../../net/ptp/core" }
ptp_proto = { path = "../../../net/ptp/proto" }
http = { path = "../../../http" }
http_util = { path = "../../../http/util" }
web = { path = "../../../web" }
rpc_util = { path = "../../../rpc/util" }
mocap_proto = { path = "../proto" }
mocap_simulation = { path = "../simulation" }
vision = { path = "../../" }
sstable = { path = "../../../sstable" }
