[package]
name = "cnc"
version = "0.1.0"
edition = "2018"

[lib]
doctest = false

[dependencies]
macros = { path = "../macros" }
protobuf = { path = "../protobuf", default-features = false }
math = { path = "../math", default-features = false }
common = { path = "../common", default-features = false }
cnc_motion_proto = { path = "./motion/proto", default-features = false }

[features]
default = ["std", "alloc"]
alloc = ["common/alloc", "math/alloc", "protobuf/alloc", "cnc_motion_proto/alloc"]
std = ["common/std", "math/std", "protobuf/std", "cnc_motion_proto/std"]