[package]
name = "home_hub"
version = "0.1.0"
authors = ["Dennis Shtatnov <densht@gmail.com>"]
edition = "2018"

[dependencies]
common = { path = "../common" }
peripheral = { path = "../peripheral" }
rpi = { path = "../rpi" }
stream_deck = { path = "../stream_deck" }
ctrlc = "3.1.1"
