[package]
name = "http_cache"
version = "0.1.0"
edition = "2018"

[dependencies]
http_cache_proto = { path = "./proto" }
base_radix = { path = "../../base/radix" }
common = { path = "../../common" }
crypto = { path = "../../crypto" }
executor = { path = "../../executor" }
executor_multitask = { path = "../../executor/multitask" }
file = { path = "../../file" }
parsing = { path = "../../parsing" }
macros = { path = "../../macros" }
protobuf = { path = "../../protobuf" }
http = { path = ".." }
http_util = { path = "../util" }
db_txn = { path = "../../db/txn" }
db_table = { path = "../../db/table" }

[features]
default = ["std"]
std = ["alloc"]
alloc = []