[package]
name = "cnc_monitor"
version = "0.1.0"
edition = "2018"

[dependencies]
base_error = { path = "../../base/error" }
base_radix = { path = "../../base/radix" }
base_units = { path = "../../base/units" }
base_util = { path = "../../base/util" }
common = { path = "../../common" }
macros = { path = "../../macros" }
protobuf = { path = "../../protobuf" }
crypto = { path = "../../crypto" }
cluster_client = { path = "../../cluster/client" }
cluster_proto = { path = "../../cluster/proto" }
executor = { path = "../../executor" }
executor_multitask = { path = "../../executor/multitask" }
db_kv = { path = "../../db/kv" }
db_table = { path = "../../db/table" }
db_txn = { path = "../../db/txn" }
file = { path = "../../file" }
rpc = { path = "../../rpc" }
rpc_util = { path = "../../rpc/util" }
usb = { path = "../../usb" }
http = { path = "../../http" }
http_util = { path = "../../http/util" }
web = { path = "../../web" }
parsing = { path = "../../parsing" }
image = { path = "../../image" }
json = { path = "../../format/json" }
cnc_monitor_proto = { path = "./proto" }
cam = { path = "../cam" }
cnc = { path = "../" }
regexp_macros = { path = "../../automata/regexp_macros" }
automata = { path = "../../automata" }
peripherals = { path = "../../peripherals" }
failure = "0.1.8"
gcode = { path = "../gcode" }
bgcode = { path = "../bgcode" }
math = { path = "../../math" }
perf = { path = "../../perf" }
net = { path = "../../net" }
graphics = { path = "../../graphics" }
media_camera = { path = "../../media/camera" }
video = { path = "../../media/video" }
compression = { path = "../../compression" }
libcamera = { path = "../../../third_party/libcamera", optional = true }
reflection = { path = "../../reflection" }

[features]
default = ["std"]
std = ["alloc"]
alloc = []
libcamera = ["dep:libcamera", "media_camera/libcamera"]