[package]
name = "meatpack"
version = "0.1.0"
edition = "2018"

[dependencies]
common = { path = "../../common" }
base_error = { path = "../../base/error" }
base_util = { path = "../../base/util" }
parsing = { path = "../../parsing" }
macros = { path = "../../macros" }
compression = { path = "../" }

[features]
default = ["std"]
std = ["alloc"]
alloc = []