syntax = "proto3";

package openpnp;

message PlacementConfig {
    repeated Part parts = 1;
}

message Part {
    string name = 1;

    // URL to a site like DigiKey where this component can be bought.
    string source = 2;

    double height = 3;

    BoardComponentReference board_ref = 4;

    bool fiducial = 5;

    // The number of degrees you need to turn the part from the feeder orientation to the
    // 0 rotation in Kicad (when the part is on the front of the board)
    // (positive is counter-clockwise).
    double rotation_offset = 6;

    FeederConfig feeder = 7;
}

message BoardComponentReference {
    repeated string value = 1;
    string package = 2;
}

message FeederConfig {
    double width = 1;
    double pitch = 2;
}