use alloc::vec::Vec;
use common::any::AsAny;
use common::ceil_div;
use core::cmp::Ord;
use core::cmp::Ordering;
use core::marker::PhantomData;
use core::ops;
use core::ops::Div;
use core::ops::Index;
use core::ops::IndexMut;
use core::ops::{Add, AddAssign};

use generic_array::{arr::AddLength, ArrayLength, GenericArray};

use crate::big::secure::raw;
use crate::big::secure::raw::{BaseType, BASE_BITS, BASE_BYTES, BITS_PER_BYTE};
use crate::big::secure::storage::*;
use crate::integer::Integer;
use crate::matrix::dimension::*;
use crate::number::{One, Zero};

/// Big unsigned integer implementation intended for security critical
/// use-cases.
///
/// Internally each instance stores a fixed size storage buffer based on the bit
/// width used to initialize the integer. All numerical operations are constant
/// time for a given storage buffer size unless otherwise specified. This means
/// that we assume that the buffer widths are publicly known and don't vary with
/// the value of the integer.
///
/// WARNING: The allocated bit width of integers is treated as public knowledge.
/// Users should always allocate integers based on their maximum possible width
/// rather than the width of the current value to maintain secrecy.
///
/// Special care must be taken to ensure that the width of integers generated by
/// operations is kept under control:
/// - Addition (a + b) will output integers with space for one extra carry bit.
/// - Multiplication (a*b) will output integers with double the space.
/// - Operations like quorem (a % b) or truncate can be used to re-contrain the
///   width of integers.
#[derive(Debug)]
pub struct SecureBigUint<S: StorageType = Vec<BaseType>> {
    /// In little endian 32bits at a time.
    /// Will be padded with
    pub(super) value: S,

    /// Exact width of 'value' in bits. May be much smaller than the size of
    /// 'value' if the value was truncated after allocation.
    bit_width: usize,
}

impl<S: StorageType + Clone> Clone for SecureBigUint<S> {
    fn clone(&self) -> Self {
        Self {
            value: self.value.clone(),
            bit_width: self.bit_width,
        }
    }
}

impl SecureBigUint<[BaseType; 1]> {
    pub const fn from_constant(value: usize) -> Self {
        let data = [value as BaseType];
        Self {
            value: data,
            bit_width: BASE_BITS,
        }
    }
}

impl<S: StorageTypeMut> SecureBigUint<S> {
    /// Creates an integer from a small value that fits within a usize. The
    /// buffer used to store this number will be able to store at least 'width'
    /// bits.
    pub fn from_usize<'a, A: Allocator<'a, Storage = S>>(
        value: usize,
        width: usize,
        allocator: &A,
    ) -> Self {
        let mut data = allocator.allocate(ceil_div(width, BASE_BITS));
        data[0] = value as BaseType;
        Self {
            value: data,
            bit_width: width,
        }
    }

    /// Creates an integer from little endian bytes representing the number.
    ///
    /// The width of the integer is inferred from data.len().
    /// The caller is responsible for ensuring that data.len() is a well known
    /// constant.
    pub fn from_le_bytes<'a, A: Allocator<'a, Storage = S>>(data: &[u8], allocator: &A) -> Self {
        let mut out = Self::from_usize(0, BITS_PER_BYTE * data.len(), allocator);

        let n = data.len() / BASE_BYTES;
        for i in 0..(data.len() / BASE_BYTES) {
            out.value[i] = BaseType::from_le_bytes(*array_ref![data, BASE_BYTES * i, BASE_BYTES]);
        }

        let rem = data.len() % BASE_BYTES;
        if rem != 0 {
            let mut rest = [0u8; BASE_BYTES];
            rest[0..rem].copy_from_slice(&data[(data.len() - rem)..]);
            out.value[n] = BaseType::from_le_bytes(rest);
        }

        out
    }

    /// Similar to from_le_bytes except uses interprates the input buffer as big
    /// endian.
    pub fn from_be_bytes<'a, A: Allocator<'a, Storage = S>>(data: &[u8], allocator: &A) -> Self {
        let mut out = Self::from_usize(0, BITS_PER_BYTE * data.len(), allocator);

        let n = data.len() / BASE_BYTES;
        for i in 0..(data.len() / BASE_BYTES) {
            out.value[i] = BaseType::from_be_bytes(*array_ref![
                data,
                data.len() - (BASE_BYTES * (i + 1)),
                BASE_BYTES
            ]);
        }

        let rem = data.len() % BASE_BYTES;
        if rem != 0 {
            let mut rest = [0u8; BASE_BYTES];
            rest[(BASE_BYTES - rem)..].copy_from_slice(&data[0..rem]);
            out.value[n] = BaseType::from_be_bytes(rest);
        }

        out
    }

    /// Computes 2^n more efficiently than using pow().
    /// Only supports exponents smaller than u32.
    /// TODO: Just take as input a u32 directly.
    pub fn exp2<'a, A: Allocator<'a, Storage = S>>(
        n: u32,
        bit_width: usize,
        allocator: &A,
    ) -> Self {
        let mut out = Self::from_usize(0, bit_width, allocator);
        out.set_bit(n as usize, 1);
        out
    }

    fn raw_mut(&mut self) -> &mut [BaseType] {
        &mut self.value.as_mut()[0..ceil_div(self.bit_width, BASE_BITS)]
    }
}

// impl<'a> Clone for SecureBigUint<'a> {
//     fn clone(&self) -> SecureBigUint<'static> {
//         SecureBigUint {
//             value: Storage::Owned(self.value.as_ref().to_vec()),
//         }
//     }
// }

impl<S: StorageType> SecureBigUint<S> {
    fn raw(&self) -> &[BaseType] {
        &self.value.as_ref()[0..ceil_div(self.bit_width, BASE_BITS)]
    }

    pub fn clone_with<'a, A: Allocator<'a>>(&self, allocator: &A) -> SecureBigUint<A::Storage> {
        // TODO: Only need to allocate enough for the current bit width.

        let mut out = SecureBigUint {
            value: allocator.allocate(self.value.as_ref().len()),
            bit_width: self.bit_width,
        };
        self.clone_to(&mut out);
        out
    }

    pub fn clone_to<S2: StorageTypeMut>(&self, out: &mut SecureBigUint<S2>) {
        // TODO: Only need to copy enough for the bit_width
        assert!(out.value.as_ref().len() >= self.raw().len());

        for i in 0..out.value.as_ref().len() {
            let v = if i < self.value.as_ref().len() {
                self.value[i]
            } else {
                0
            };

            out.value[i] = v;
        }

        out.bit_width = self.bit_width;
    }

    /// Converts the integer to little endian bytes.
    ///
    /// NOTE: This may have zero significant padding depending on the internal
    /// representation.
    pub fn to_le_bytes(&self) -> Vec<u8> {
        let mut data = vec![];
        data.reserve_exact(self.value.as_ref().len() * BASE_BYTES);
        for v in self.value.as_ref() {
            data.extend_from_slice(&v.to_le_bytes());
        }

        data.truncate(self.byte_width());

        data
    }

    pub fn to_be_bytes(&self) -> Vec<u8> {
        let mut data = vec![];
        data.reserve_exact(self.value.as_ref().len() * BASE_BYTES);
        for v in self.value.as_ref().iter().rev() {
            data.extend_from_slice(&v.to_be_bytes());
        }

        data = data.split_off(data.len() - self.byte_width());

        data
    }

    /// Computes 'output = self + rhs'. It is the user's responsibility to
    /// ensure that the
    pub fn add_to<S2: StorageType, S3: StorageTypeMut>(
        &self,
        rhs: &SecureBigUint<S2>,
        output: &mut SecureBigUint<S3>,
    ) {
        raw::add_to_impl(
            self.value.as_ref(),
            rhs.value.as_ref(),
            output.value.as_mut(),
        );
    }

    /// Computes and returns 'self + rhs'. The output buffer will be 1 bit
    /// larger than the inputs to accomadate possible overflow.
    pub fn add<'a, S2: StorageType, A: Allocator<'a>>(
        &self,
        rhs: &SecureBigUint<S2>,
        allocator: &A,
    ) -> SecureBigUint<A::Storage> {
        let mut out = SecureBigUint::from_usize(
            0,
            core::cmp::max(self.bit_width(), rhs.bit_width()) + 1,
            allocator,
        );
        self.add_to(rhs, &mut out);
        out
    }

    pub fn sub<'a, A: Allocator<'a>, S2: StorageType>(
        &self,
        rhs: &SecureBigUint<S2>,
        allocator: &A,
    ) -> SecureBigUint<A::Storage> {
        let mut out = self.clone_with(allocator);
        out.sub_assign(rhs);
        out
    }

    pub fn mul<'a, S2: StorageType, A: Allocator<'a>>(
        &self,
        rhs: &SecureBigUint<S2>,
        allocator: &A,
    ) -> SecureBigUint<A::Storage> {
        let mut out = SecureBigUint::from_usize(0, self.bit_width() + rhs.bit_width(), allocator);
        self.mul_to(rhs, &mut out);
        out
    }

    pub fn mul_to<S2: StorageType, S3: StorageTypeMut>(
        &self,
        rhs: &SecureBigUint<S2>,
        out: &mut SecureBigUint<S3>,
    ) {
        raw::mul_to_impl(self.value.as_ref(), rhs.value.as_ref(), out.value.as_mut());
    }

    pub fn bit(&self, i: usize) -> usize {
        ((self.value[i / BASE_BITS] >> (i % BASE_BITS)) & 0b01) as usize
    }

    /// Computes the quotient and remainder of 'self / rhs'.
    ///
    /// Any mixture of input bit_widths is supported.
    /// Internally this uses binary long division.
    ///
    /// NOTE: This is very slow and should be avoided if possible.
    ///
    /// Returns a tuple of '(self / rhs, self % rhs)' where the quotient is the
    /// same width as 'self' and the remainder is the same width as 'rhs'.
    pub fn quorem<'a, S2: StorageType, A: Allocator<'a>>(
        &self,
        rhs: &SecureBigUint<S2>,
        allocator: &mut A,
    ) -> (SecureBigUint<A::Storage>, SecureBigUint<A::Storage>) {
        let mut q = SecureBigUint::from_usize(0, self.bit_width(), allocator); // Range is [0, Self]
        let mut r = SecureBigUint::from_usize(0, rhs.bit_width(), allocator); // Range is [0, rhs).

        let sub_allocator = allocator.sub_allocator();

        // TODO: Implement a bit iterator so set_bit requires less work.
        for i in (0..self.bit_width()).rev() {
            let carry = r.shl();
            r.set_bit(0, self.bit(i));

            let mut next_r = SecureBigUint::from_usize(0, rhs.bit_width(), &sub_allocator);

            // If there is a carry, then we know that r might be > rhs when the shl also has
            // a carry.
            let carry2 = r.overflowing_sub_to(rhs, &mut next_r);

            let subtract = (carry != 0) == carry2;

            next_r.copy_if(subtract, &mut r);

            q.set_bit(i, if subtract { 1 } else { 0 });
        }

        (q, r)
    }

    pub fn rem<'a, S2: StorageType, A: Allocator<'a>>(
        &self,
        rhs: &SecureBigUint<S2>,
        allocator: &mut A,
    ) -> SecureBigUint<A::Storage> {
        self.quorem(rhs, allocator).1
    }

    /// WARNING: This is not constant time and probably will reveal information
    /// about the number.
    pub fn value_bits(&self) -> usize {
        for i in (0..self.value.as_ref().len()).rev() {
            let zeros = self.value[i].leading_zeros() as usize;
            if zeros == BASE_BITS {
                continue;
            }

            return (i * BASE_BITS) + (BASE_BITS - zeros);
        }

        0
    }

    pub fn bit_width(&self) -> usize {
        // TODO: Use self.bit_width

        // return self.bit_width;

        // if self.bit_width != raw::bit_width_impl(self.value.as_ref()) {
        //     println!(
        //         "{} {}",
        //         self.bit_width,
        //         raw::bit_width_impl(self.value.as_ref())
        //     );
        // }

        // assert_eq!(self.bit_width, raw::bit_width_impl(self.value.as_ref()));

        raw::bit_width_impl(self.value.as_ref())

        // self.bit_width
    }

    pub fn byte_width(&self) -> usize {
        self.value.as_ref().len() * BASE_BYTES

        // ceil_div(self.bit_width, BITS_PER_BYTE)
    }

    /// Multiplies two numbers and adds their result to the out number.
    /// out += self*rhs
    pub(super) fn add_mul_to<S2: StorageType, S3: StorageTypeMut>(
        &self,
        rhs: &SecureBigUint<S2>,
        out: &mut SecureBigUint<S3>,
    ) {
        raw::add_mul_to_impl(self.value.as_ref(), rhs.value.as_ref(), out.value.as_mut());
    }

    /// Copies 'self' to 'out' if should_copy is true. In all cases, this takes
    /// a constant amount of time to execute.
    ///
    /// NOTE: 'self' and 'out' must have the same bit_width().
    pub fn copy_if<S2: StorageTypeMut>(&self, should_copy: bool, out: &mut SecureBigUint<S2>) {
        raw::copy_if_impl(self.value.as_ref(), should_copy, out.value.as_mut());
        out.bit_width = core::cmp::max(self.bit_width, out.bit_width);
    }

    pub fn is_zero(&self) -> bool {
        let mut is = true;

        for v in self.value.as_ref() {
            is &= *v == 0;
        }

        is
    }

    pub(super) fn overflowing_sub_to<S2: StorageType, S3: StorageTypeMut>(
        &self,
        rhs: &SecureBigUint<S2>,
        out: &mut SecureBigUint<S3>,
    ) -> bool {
        raw::overflowing_sub_to_impl(self.value.as_ref(), rhs.value.as_ref(), out.value.as_mut())
    }

    /// Efficienctly (in O(1) time) computes 'self % 2^32'
    pub fn mod_word(&self) -> BaseType {
        if self.value.as_ref().len() == 0 {
            0
        } else {
            self.value[0]
        }
    }

    // TODO: Need a version of this using pmull in aarch64 (vmull_p64)

    /// Interprates this integer and 'rhs' as polynomials over GF(2^n) and
    /// multiplies them into 'out'.
    ///
    /// Operations in this field:
    /// - Addition is XOR
    /// - Multiplication is AND
    pub fn carryless_mul_to<S2: StorageType, S3: StorageTypeMut>(
        &self,
        rhs: &SecureBigUint<S2>,
        out: &mut SecureBigUint<S3>,
    ) {
        raw::carryless_mul_to_impl(self.value.as_ref(), rhs.value.as_ref(), out.value.as_mut());
    }

    // TODO: Move to a shared utility.
    pub fn to_string_radix(&self, radix: u32) -> alloc::string::String {
        let mut allocator = HeapAllocator {};

        // TODO: These should be global constants (as well as one)
        let zero = SecureBigUint::from_usize(0, self.bit_width(), &allocator);
        let div = SecureBigUint::from_usize(radix as usize, 32, &allocator);

        let mut s = alloc::string::String::new();
        let mut tmp = self.clone_with(&allocator);
        while tmp > zero {
            // TODO: We can divide by a larger power of 10 to make this more efficient.
            let (q, r) = tmp.quorem(&div, &mut allocator);
            tmp = q;
            // TODO: Very inefficient
            s.insert(
                0,
                core::char::from_digit(r.value.first().cloned().unwrap_or(0), radix).unwrap(),
            );
        }

        if s.len() == 0 {
            s.push('0');
        }

        s
    }
}

impl<S: StorageTypeMut> SecureBigUint<S> {
    /// Computes 'self += rhs'.
    pub fn add_assign<S2: StorageType>(&mut self, rhs: &SecureBigUint<S2>) {
        raw::add_assign_impl(self.value.as_mut(), rhs.value.as_ref());
    }

    /// It would be useful to have a conditional form of this that adds like
    /// subtraction by zero.
    pub fn sub_assign<S2: StorageType>(&mut self, rhs: &SecureBigUint<S2>) {
        assert!(!self.overflowing_sub_assign(rhs));
    }

    pub fn set_bit(&mut self, i: usize, v: usize) {
        assert!(v == 0 || v == 1);
        let ii = i / BASE_BITS;
        let shift = i % BASE_BITS;
        let mask = !(1 << shift);

        self.value[ii] = (self.value[ii] & mask) | ((v as BaseType) << shift);
    }

    /// Swaps the contents of 'self' and 'other' if 'should_swap' is true.
    ///
    /// The actual values of both integers are swapped rather than swapping any
    /// internal memory pointers so that 'should_swap' can not be inferred from
    /// the memory locations of the final integers.
    ///
    /// At a given integer bit_width, this should always take the same amount of
    /// CPU cycles to execute.
    pub fn swap_if<S2: StorageTypeMut>(
        &mut self,
        other: &mut SecureBigUint<S2>,
        should_swap: bool,
    ) {
        raw::swap_if_impl(self.value.as_mut(), other.value.as_mut(), should_swap);

        self.bit_width = core::cmp::max(self.bit_width, other.bit_width);
        other.bit_width = self.bit_width;
    }

    /// In-place reverses all the order of all bits in this integer.
    pub fn reverse_bits(&mut self) {
        raw::reverse_bits_impl(self.value.as_mut());
    }

    /// Performs 'self ^= rhs' only if 'should_apply' is true.
    pub fn xor_assign_if<S2: StorageType>(&mut self, should_apply: bool, rhs: &SecureBigUint<S2>) {
        raw::xor_assign_if_impl(self.value.as_mut(), should_apply, rhs.value.as_ref());
    }

    /*
    pub fn discard(&mut self, bit_width: usize) {
        let n = ceil_div(bit_width, BASE_BITS);
        self.value.truncate(n);
    }
    */

    ///
    pub fn truncate(&mut self, bit_width: usize) {
        assert!(self.bit_width >= bit_width);
        if self.bit_width == bit_width {
            return;
        }

        let n = ceil_div(bit_width, BASE_BITS);

        // TODO: Also zero out any high bits

        for i in n..self.value.as_ref().len() {
            assert_eq!(self.value[i], 0);
        }

        self.value.truncate(n);

        self.bit_width = bit_width;
    }

    /// TODO: Improve the constant time behavior of this.
    /// It would be useful to have a conditional form of this that adds like
    /// subtraction by zero.
    pub(super) fn overflowing_sub_assign<S2: StorageType>(
        &mut self,
        rhs: &SecureBigUint<S2>,
    ) -> bool {
        raw::overflowing_sub_assign_impl(self.value.as_mut(), rhs.value.as_ref())
    }

    /// Performs modular reduction using up to one subtraction of the modulus
    /// from the value.
    ///
    /// Will panic if 'self' was >= 2*modulus
    pub fn reduce_once<'a, S2: StorageType, A: Allocator<'a>>(
        &mut self,
        modulus: &SecureBigUint<S2>,
        allocator: &A,
    ) {
        let mut reduced = SecureBigUint::from_usize(0, self.bit_width(), allocator);
        let overflow = self.overflowing_sub_to(modulus, &mut reduced);
        reduced.copy_if(!overflow, self);
        self.truncate(modulus.bit_width());
    }

    #[must_use]
    pub fn shl(&mut self) -> BaseType {
        raw::shl_impl(self.value.as_mut())
    }

    pub fn shr(&mut self) {
        raw::shr_impl(self.value.as_mut())
    }

    /// Computes 'self >>= n'
    /// NOTE: We assume that 'n' is a publicly known constant.
    pub fn shr_n(&mut self, n: usize) {
        raw::shr_n_impl(self.value.as_mut(), n)
    }

    /// Computes self >>= BASE_BITS.
    pub(super) fn shr_base(&mut self) {
        raw::shr_base_impl(self.value.as_mut())
    }

    pub fn and_assign<S2: StorageType>(&mut self, rhs: &SecureBigUint<S2>) {
        raw::and_assign_impl(self.value.as_mut(), rhs.value.as_ref())
    }

    /// Resets the value of the integer to 0.
    pub fn assign_zero(&mut self) {
        for v in self.value.as_mut().iter_mut() {
            *v = 0;
        }
    }

    /// In-place increases the size
    pub fn extend<'a, A: Allocator<'a, Storage = S>>(
        &mut self,
        bit_width: usize,
        allocator: &mut A,
    ) {
        let cur_len = self.value.as_ref().len();
        let new_len = ceil_div(bit_width, BASE_BITS);
        assert!(new_len >= cur_len);

        if new_len > cur_len {
            let mut new_value = allocator.allocate(new_len);
            new_value.as_mut()[0..cur_len].copy_from_slice(self.value.as_ref());
            self.value = new_value;
        }
    }

    // TODO: Optimize with sub allocations.
    pub fn from_str<'a, A: Allocator<'a, Storage = S>>(
        s: &str,
        bit_width: usize,
        allocator: &A,
    ) -> common::errors::Result<Self> {
        let ten = SecureBigUint::from_usize(10, 32, allocator);

        let mut out = SecureBigUint::from_usize(0, bit_width, allocator);
        for c in s.chars() {
            let digit = c
                .to_digit(10)
                .ok_or(common::errors::err_msg("Invalid digit"))?;

            let tmp = out.clone_with(allocator);
            ten.mul_to(&tmp, &mut out);

            out += SecureBigUint::from_usize(digit as usize, bit_width, allocator);

            // out = (&out * &ten) + &(digit as usize).into();
        }

        Ok(out)
    }
}

impl<S: StorageType> core::fmt::Display for SecureBigUint<S> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}", self.to_string_radix(10))
    }
}

impl<S: StorageType> Ord for SecureBigUint<S> {
    fn cmp(&self, other: &Self) -> Ordering {
        raw::cmp_impl(self.value.as_ref(), other.value.as_ref())
    }
}

impl<S: StorageType, S2: StorageType> PartialEq<SecureBigUint<S2>> for SecureBigUint<S> {
    fn eq(&self, other: &SecureBigUint<S2>) -> bool {
        raw::cmp_impl(self.value.as_ref(), other.value.as_ref()) == Ordering::Equal
    }
}
impl<S: StorageType> Eq for SecureBigUint<S> {}

impl<S: StorageType, S2: StorageType> PartialOrd<SecureBigUint<S2>> for SecureBigUint<S> {
    fn partial_cmp(&self, other: &SecureBigUint<S2>) -> Option<Ordering> {
        Some(raw::cmp_impl(self.value.as_ref(), other.value.as_ref()))
    }
}

//
// Addition
//

impl<S: StorageTypeMut, S2: StorageType> Add<SecureBigUint<S2>> for SecureBigUint<S> {
    type Output = Self;

    fn add(mut self, rhs: SecureBigUint<S2>) -> Self {
        raw::add_assign_impl(self.value.as_mut(), rhs.value.as_ref());
        self
    }
}

impl<S: StorageTypeMut, S2: StorageType> Add<&SecureBigUint<S2>> for SecureBigUint<S> {
    type Output = Self;

    fn add(mut self, rhs: &SecureBigUint<S2>) -> Self {
        raw::add_assign_impl(self.value.as_mut(), rhs.value.as_ref());
        self
    }
}

impl<S: StorageTypeMut, S2: StorageType> AddAssign<SecureBigUint<S2>> for SecureBigUint<S> {
    fn add_assign(&mut self, rhs: SecureBigUint<S2>) {
        raw::add_assign_impl(self.value.as_mut(), rhs.value.as_ref())
    }
}

impl<S: StorageTypeMut, S2: StorageType> AddAssign<&SecureBigUint<S2>> for SecureBigUint<S> {
    fn add_assign(&mut self, rhs: &SecureBigUint<S2>) {
        raw::add_assign_impl(self.value.as_mut(), rhs.value.as_ref())
    }
}

//
// Subtraction
//

use core::ops::{Sub, SubAssign};

impl<S: StorageTypeMut, S2: StorageType> Sub<SecureBigUint<S2>> for SecureBigUint<S> {
    type Output = Self;

    fn sub(mut self, rhs: SecureBigUint<S2>) -> Self {
        assert!(!raw::overflowing_sub_assign_impl(
            self.value.as_mut(),
            rhs.value.as_ref()
        ));
        self
    }
}

impl<S: StorageTypeMut, S2: StorageType> Sub<&SecureBigUint<S2>> for SecureBigUint<S> {
    type Output = Self;

    fn sub(mut self, rhs: &SecureBigUint<S2>) -> Self {
        assert!(!raw::overflowing_sub_assign_impl(
            self.value.as_mut(),
            rhs.value.as_ref()
        ));
        self
    }
}

impl<S: StorageTypeMut, S2: StorageType> SubAssign<SecureBigUint<S2>> for SecureBigUint<S> {
    fn sub_assign(&mut self, rhs: SecureBigUint<S2>) {
        assert!(!raw::overflowing_sub_assign_impl(
            self.value.as_mut(),
            rhs.value.as_ref()
        ));
    }
}

impl<S: StorageTypeMut, S2: StorageType> SubAssign<&SecureBigUint<S2>> for SecureBigUint<S> {
    fn sub_assign(&mut self, rhs: &SecureBigUint<S2>) {
        assert!(!raw::overflowing_sub_assign_impl(
            self.value.as_mut(),
            rhs.value.as_ref()
        ));
    }
}

/*
impl_op_ex!(+= |lhs: &mut SecureBigUint, rhs: &SecureBigUint| {
    Integer::add_assign(lhs, rhs)
});

impl_op_commutative!(+ |lhs: SecureBigUint, rhs: &SecureBigUint| -> SecureBigUint {
    // NOTE: Does not use add_into to avoid risking an overflow.
    Integer::add(&lhs, rhs)
});

impl_op!(+ |lhs: &SecureBigUint, rhs: &SecureBigUint| -> SecureBigUint {
    Integer::add(lhs, rhs)
});

impl_op_ex!(-= |lhs: &mut SecureBigUint, rhs: &SecureBigUint| {
    Integer::sub_assign(lhs, rhs)
});

impl_op_ex!(-|lhs: SecureBigUint, rhs: &SecureBigUint| -> SecureBigUint { lhs.sub_into(rhs) });

impl_op!(-|lhs: &SecureBigUint, rhs: &SecureBigUint| -> SecureBigUint { Integer::sub(lhs, rhs) });

impl_op_ex!(
    *|lhs: &SecureBigUint, rhs: &SecureBigUint| -> SecureBigUint { Integer::mul(lhs, rhs) }
);

impl_op_ex!(/ |lhs: &SecureBigUint, rhs: &SecureBigUint| -> SecureBigUint {
    let (q, _) = lhs.quorem(rhs);
    q
});

impl_op!(% |lhs: SecureBigUint, rhs: &SecureBigUint| -> SecureBigUint {
    let (_, r) = lhs.quorem(rhs);
    r
});

impl_op!(% |lhs: &SecureBigUint, rhs: &SecureBigUint| -> SecureBigUint {
    let (_, r) = lhs.quorem(rhs);
    r
});

impl_op_ex!(^= |lhs: &mut SecureBigUint, rhs: &SecureBigUint| {
    assert_eq!(lhs.value.len(), rhs.value.len());

    for (lhs_value, rhs_value) in lhs.value.iter_mut().zip(rhs.value.iter()) {
        *lhs_value ^= *rhs_value;
    }
});
*/
use core::ops::BitXorAssign;

impl<S: StorageTypeMut, S2: StorageType> BitXorAssign<SecureBigUint<S2>> for SecureBigUint<S> {
    fn bitxor_assign(&mut self, rhs: SecureBigUint<S2>) {
        raw::xor_assign_impl(self.value.as_mut(), rhs.value.as_ref())
    }
}

impl<S: StorageTypeMut, S2: StorageType> BitXorAssign<&SecureBigUint<S2>> for SecureBigUint<S> {
    fn bitxor_assign(&mut self, rhs: &SecureBigUint<S2>) {
        raw::xor_assign_impl(self.value.as_mut(), rhs.value.as_ref())
    }
}

/*
impl_op_ex!(^ |lhs: &SecureBigUint, rhs: &SecureBigUint| -> SecureBigUint {
    assert_eq!(lhs.value.len(), rhs.value.len());

    let mut out = SecureBigUint::from_usize(0, lhs.bit_width());

    for i in 0..out.value.len() {
        out.value[i] = lhs.value[i] ^ rhs.value[i];
    }

    out
});
*/

#[cfg(test)]
mod tests {
    use super::*;
    use core::str::FromStr;

    #[test]
    fn secure_biguint_test() {
        // TODO: Check multiplication in x*0 and x*1 cases

        let seven = SecureBigUint::from_usize(7, 64, &mut HeapAllocator {});
        let one_hundred = SecureBigUint::from_usize(100, 64, &mut HeapAllocator {});

        assert!(one_hundred > seven);
        assert!(seven < one_hundred);
        assert!(one_hundred == one_hundred);
        assert!(seven == seven);

        let mut seven_hundred = SecureBigUint::from_usize(0, 128, &mut HeapAllocator {});
        seven.mul_to(&one_hundred, &mut seven_hundred);

        assert!(seven_hundred == SecureBigUint::from_usize(700, 64, &mut HeapAllocator {}));

        let x = SecureBigUint::from_le_bytes(&[0xff, 0xff, 0xff, 0xff], &mut HeapAllocator {});
        let mut temp = SecureBigUint::from_usize(0, 64, &mut HeapAllocator {});
        x.mul_to(&x, &mut temp);

        assert_eq!(
            &temp.to_le_bytes(),
            &(core::u32::MAX as u64).pow(2).to_le_bytes()
        );

        let (q, r) = temp.quorem(&x, &mut HeapAllocator {});

        // Equal to 'x' extended to 64 bits
        assert!(
            q == SecureBigUint::from_le_bytes(
                &[0xff, 0xff, 0xff, 0xff, 0, 0, 0, 0],
                &mut HeapAllocator {}
            )
        );

        assert!(r == SecureBigUint::from_usize(0, 32, &mut HeapAllocator {}));

        let (q, r) = one_hundred.quorem(&seven, &mut HeapAllocator {});
        assert!(q == SecureBigUint::from_usize(14, 64, &mut HeapAllocator {}));
        assert!(r == SecureBigUint::from_usize(2, 64, &mut HeapAllocator {}));

        let (q, r) = seven.quorem(&one_hundred, &mut HeapAllocator {});
        assert!(q == SecureBigUint::from_usize(0, 64, &mut HeapAllocator {}));
        assert!(r == SecureBigUint::from_usize(7, 64, &mut HeapAllocator {}));

        // TODO: Test larger numbers.
    }

    #[test]
    fn shr_n_test() {
        {
            let mut v = SecureBigUint::from_be_bytes(&[0b00010100, 0, 0, 0], &mut HeapAllocator {});
            v.shr_n(1);
            assert_eq!(&v.to_be_bytes(), &[0b00001010, 0, 0, 0]);
        }

        {
            let mut v = SecureBigUint::from_be_bytes(&[0b00010100, 0, 0, 0], &mut HeapAllocator {});
            v.shr_n(8);
            assert_eq!(&v.to_be_bytes(), &[0, 0b00010100, 0, 0]);
        }

        // Testing moving values across bases.
        {
            let mut v = SecureBigUint::from_be_bytes(
                &[0b00010100, 0, 0, 0, 0, 0, 0, 0],
                &mut HeapAllocator {},
            );
            v.shr_n(32);
            assert_eq!(&v.to_be_bytes(), &[0, 0, 0, 0, 0b00010100, 0, 0, 0]);
        }

        {
            let mut v = SecureBigUint::from_be_bytes(
                &[0b00010100, 0, 0, 0, 0, 0, 0, 0],
                &mut HeapAllocator {},
            );
            v.shr_n(34);
            assert_eq!(&v.to_be_bytes(), &[0, 0, 0, 0, 0b00000101, 0, 0, 0]);
        }

        // Carry to second base.
        {
            let mut v =
                SecureBigUint::from_be_bytes(&[0, 0, 0, 1, 0, 0, 0, 0], &mut HeapAllocator {});
            v.shr_n(1);
            assert_eq!(&v.to_be_bytes(), &[0, 0, 0, 0, 0b10000000, 0, 0, 0]);
        }
    }
}
