[package]
name = "asn_compiler"
version = "0.0.0"
edition = "2018"

[dependencies]
common = { path = "../../common" }
file = { path = "../../file" }
parsing = { path = "../../parsing" }
base_radix = { path = "../../base/radix" }
