# proto-file: pkg/builder/proto/config.proto
# proto-message: BuildConfig

platform {
    os: LINUX
    architecture: AMD64
}

rule_defaults {
    [type.googleapis.com/builder.RustBinaryAttrs] {
        compiler: CARGO
        profile: "release"
        target: "x86_64-unknown-linux-gnu"
        rustflags: "-C target_feature=aes -C target_feature=pclmulqdq -C target_feature=sse4.2"
    }
}
