name: "system.meta"
replicas: 1
scheduling {
    distinct_nodes: true
}
worker {
    persistent: true

    args: [
        "/volumes/bundle/built/pkg/cluster/meta/cluster_meta",
        "--port=rpc",
        "--dir=/volumes/data"
    ]

    ports {
        name: "rpc"
        type: TCP
    }

    volumes: [
        {
            name: "bundle"
            build_target: "//pkg/cluster/meta:cluster_meta_bundle"
        },
        {
            name: "data"
            persistent: true
        }
    ]
}