[package]
name = "screen_grabber"
version = "0.1.0"
edition = "2018"

[dependencies]
base_error = { path = "../../base/error" }
common = { path = "../../common" }
image = { path = "../../image" }
executor = { path = "../../executor" }
executor_multitask = { path = "../../executor/multitask" }
file = { path = "../../file" }
crypto = { path = "../../crypto" }
cluster_client = { path = "../../container/client" }
container_proto = { path = "../../container/proto" }
macros = { path = "../../macros" }
http = { path = "../../http" }
http_util = { path = "../../http/util" }
json = { path = "../../format/json" }
web = { path = "../../web" }
protobuf = { path = "../../protobuf" }
parsing = { path = "../../parsing" }
screen_grabber_proto = { path = "./proto" }
rpc = { path = "../../rpc" }
rpc_util = { path = "../../rpc/util" }
google_auth = { path = "../../api/google/auth" }
gemini = { path = "../../api/google/gemini" }
x11 = { path = "../../../third_party/x11" }
