syntax = "proto3";

package media.camera;

import "pkg/media/camera/proto/property.proto";

service CameraInterface {
    rpc ListCameras (ListCamerasRequest) returns (ListCamerasResponse);

    rpc GetProperties (GetPropertiesRequest) returns (GetPropertiesResponse);

    rpc SetProperties (SetPropertiesRequest) returns (SetPropertiesResponse);
}

message ListCamerasRequest {
    
}

message ListCamerasResponse {
    repeated CameraEntryProto entries = 1;
}

message CameraEntryProto {
    string id = 1;
    string name = 2;
}

message GetPropertiesRequest {
    string camera_id = 1;
}

message GetPropertiesResponse {
    Properties properties = 1;

    CameraFormat format = 2;
}

message CameraFormat {
    enum LiveStreamFormat {
        UNKNOWN = 0;
        MP4 = 1;
        MJPEG = 2;
    }

    // Format that will be used if an HTTP stream is requested with the live data from the camera. 
    LiveStreamFormat live_format = 1;
}



message SetPropertiesRequest {
    string camera_id = 1;

    // Note that only the values in these properties are read.
    // Attempts to change the property specs are ignored.
    Properties properties = 2;
}

message SetPropertiesResponse {

}