[package]
name = "uf2"
version = "0.1.0"
edition = "2018"

[dependencies]
common = { path = "../../common", default-features = false }
crypto = { path = "../../crypto", default-features = false }

[features]
default = ["std", "alloc"]
alloc = ["common/alloc", "crypto/alloc"]
std = ["common/std", "crypto/std"]